set(HSM_CONFIG_FILE hsm_config.txt)
set(HSM_COMMAND ${TEST_CMD} ${HSM_CONFIG_FILE})

set(U_GENERATE_001_NAME U_HSM_Generate_001)
set(U_GENERATE_001_DEF ${SMW_TESTS_TARGET_DEF_DIR_FULL_PATH}/${U_GENERATE_001_NAME}.json)
set(U_GENERATE_001_CMD ${HSM_COMMAND} ${U_GENERATE_001_DEF})
add_test(NAME ${U_GENERATE_001_NAME} COMMAND ${U_GENERATE_001_CMD})
set_tests_properties(${U_GENERATE_001_NAME} PROPERTIES LABELS
		     "${UNITARY_LABEL};${HSM_LABEL};${GENERATE_LABEL}")

set(U_EXPORT_001_NAME U_HSM_Export_001)
set(U_EXPORT_001_DEF ${SMW_TESTS_TARGET_DEF_DIR_FULL_PATH}/${U_EXPORT_001_NAME}.json)
set(U_EXPORT_001_CMD ${HSM_COMMAND} ${U_EXPORT_001_DEF})
add_test(NAME ${U_EXPORT_001_NAME} COMMAND ${U_EXPORT_001_CMD})
set_tests_properties(${U_EXPORT_001_NAME} PROPERTIES LABELS
		     "${UNITARY_LABEL};${HSM_LABEL};${EXPORT_LABEL}")

set(U_HASH_001_NAME U_HSM_Hash_001)
set(U_HASH_001_DEF ${SMW_TESTS_TARGET_DEF_DIR_FULL_PATH}/${U_HASH_001_NAME}.json)
set(U_HASH_001_CMD ${HSM_COMMAND} ${U_HASH_001_DEF})
add_test(NAME ${U_HASH_001_NAME} COMMAND ${U_HASH_001_CMD})
set_tests_properties(${U_HASH_001_NAME} PROPERTIES LABELS
		     "${UNITARY_LABEL};${HSM_LABEL};${HASH_LABEL}")

set(U_SIGN_VERIFY_001_NAME U_HSM_Sign_Verify_001)
set(U_SIGN_VERIFY_001_DEF ${SMW_TESTS_TARGET_DEF_DIR_FULL_PATH}/${U_SIGN_VERIFY_001_NAME}.json)
set(U_SIGN_VERIFY_001_CMD ${HSM_COMMAND} ${U_SIGN_VERIFY_001_DEF})
add_test(NAME ${U_SIGN_VERIFY_001_NAME} COMMAND ${U_SIGN_VERIFY_001_CMD})
set_tests_properties(${U_SIGN_VERIFY_001_NAME} PROPERTIES LABELS
		     "${UNITARY_LABEL};${HSM_LABEL};${SIGN_LABEL};${VERIFY_LABEL}")

install(FILES ${SMW_CONFIG_SRC_DIR}/${HSM_CONFIG_FILE}
        DESTINATION ${SMW_TESTS_TARGET_CONFIG_DIR}
        EXCLUDE_FROM_ALL
        COMPONENT ${PROJECT_NAME})

FILE(GLOB U_HSM_TEST ${TEST_DEF_SRC_DIR}/U_HSM*.json)

foreach(file IN LISTS U_HSM_TEST)
    install(FILES ${file}
            DESTINATION ${SMW_TESTS_TARGET_DEF_DIR}
            EXCLUDE_FROM_ALL
            COMPONENT ${PROJECT_NAME})
endforeach()
