set(HSM_CONFIG_FILE hsm_config.txt)
set(HSM_COMMAND ${TEST_CMD} ${HSM_CONFIG_FILE})
set(HSM_TEST_KEYMGR_SUSPEND_RESUME_COMMAND ${TEST_KEYMGR_SUSPEND_RESUME_CMD} ${HSM_CONFIG_FILE})

# Install config file
install(FILES ${SMW_CONFIG_SRC_DIR}/${HSM_CONFIG_FILE}
	DESTINATION ${SMW_TESTS_TARGET_CONFIG_DIR}
	EXCLUDE_FROM_ALL
	COMPONENT ${PROJECT_NAME})

# Get all HSM test definition files except those in multiple parts
FILE(GLOB HSM_TESTS ${TEST_DEF_SRC_DIR}/*_HSM_*_???.json)

if(ENABLE_TLS12)
	set(U_TLS_001 U_HSM_TLS_001.json)
	list(REMOVE_ITEM HSM_TESTS ${TEST_DEF_SRC_DIR}/${U_TLS_001})
else()
	set(U_DERIVE_001 U_HSM_Derive_001.json)
	set(F_TLS_001 F_HSM_TLS_001.json)
	list(REMOVE_ITEM HSM_TESTS
	     ${TEST_DEF_SRC_DIR}/${U_DERIVE_001})
	list(REMOVE_ITEM HSM_TESTS ${TEST_DEF_SRC_DIR}/${F_TLS_001})
endif()

add_and_install_tests("${HSM_TESTS}" "${HSM_COMMAND}")

# Create suspend resume test definition files list and install test
set(F_KEYMGR_001_1 F_HSM_Keymgr_001.1.json)
set(F_KEYMGR_001_2 F_HSM_Keymgr_001.2.json)

list(APPEND HSM_SUSPEND_RESUME_TESTS ${TEST_DEF_SRC_DIR}/${F_KEYMGR_001_1})
list(APPEND HSM_SUSPEND_RESUME_TESTS ${TEST_DEF_SRC_DIR}/${F_KEYMGR_001_2})

add_and_install_tests("${HSM_SUSPEND_RESUME_TESTS}"
		      "${HSM_TEST_KEYMGR_SUSPEND_RESUME_COMMAND}")
