set(TEE_CONFIG_FILE tee_config.txt)
set(TEE_COMMAND ${TEST_CMD} ${TEE_CONFIG_FILE})

set(U_GENERATE_001_NAME U_TEE_Generate_001)
set(U_GENERATE_001_DEF ${SMW_TESTS_TARGET_DEF_DIR_FULL_PATH}/${U_GENERATE_001_NAME}.json)
set(U_GENERATE_001_CMD ${TEE_COMMAND} ${U_GENERATE_001_DEF})
add_test(NAME ${U_GENERATE_001_NAME} COMMAND ${U_GENERATE_001_CMD})
set_tests_properties(${U_GENERATE_001_NAME} PROPERTIES LABELS
		     "${UNITARY_LABEL};${TEE_LABEL};${GENERATE_LABEL}")

set(U_IMPORT_001_NAME U_TEE_Import_001)
set(U_IMPORT_001_DEF ${SMW_TESTS_TARGET_DEF_DIR_FULL_PATH}/${U_IMPORT_001_NAME}.json)
set(U_IMPORT_001_CMD ${TEE_COMMAND} ${U_IMPORT_001_DEF})
add_test(NAME ${U_IMPORT_001_NAME} COMMAND ${U_IMPORT_001_CMD})
set_tests_properties(${U_IMPORT_001_NAME} PROPERTIES LABELS
		     "${UNITARY_LABEL};${TEE_LABEL};${IMPORT_LABEL}")

set(U_IMPORT_002_NAME U_TEE_Import_002)
set(U_IMPORT_002_DEF ${SMW_TESTS_TARGET_DEF_DIR_FULL_PATH}/${U_IMPORT_002_NAME}.json)
set(U_IMPORT_002_CMD ${TEE_COMMAND} ${U_IMPORT_002_DEF})
add_test(NAME ${U_IMPORT_002_NAME} COMMAND ${U_IMPORT_002_CMD})
set_tests_properties(${U_IMPORT_002_NAME} PROPERTIES LABELS
		     "${UNITARY_LABEL};${TEE_LABEL};${IMPORT_LABEL}")

set(U_EXPORT_001_NAME U_TEE_Export_001)
set(U_EXPORT_001_DEF ${SMW_TESTS_TARGET_DEF_DIR_FULL_PATH}/${U_EXPORT_001_NAME}.json)
set(U_EXPORT_001_CMD ${TEE_COMMAND} ${U_EXPORT_001_DEF})
add_test(NAME ${U_EXPORT_001_NAME} COMMAND ${U_EXPORT_001_CMD})
set_tests_properties(${U_EXPORT_001_NAME} PROPERTIES LABELS
		     "${UNITARY_LABEL};${TEE_LABEL};${EXPORT_LABEL}")

set(F_KEYMGR_001_NAME F_TEE_Keymgr_001)
set(F_KEYMGR_001_DEF ${SMW_TESTS_TARGET_DEF_DIR_FULL_PATH}/${F_KEYMGR_001_NAME}.json)
set(F_KEYMGR_001_CMD ${TEE_COMMAND} ${F_KEYMGR_001_DEF})
add_test(NAME ${F_KEYMGR_001_NAME} COMMAND ${F_KEYMGR_001_CMD})
set_tests_properties(${F_KEYMGR_001_NAME} PROPERTIES LABELS
		     "${FUNCTIONAL_LABEL};${TEE_LABEL};${KEYMGR_LABEL}")

set(F_KEYMGR_002_NAME F_TEE_Keymgr_002)
set(F_KEYMGR_002_DEF ${SMW_TESTS_TARGET_DEF_DIR_FULL_PATH}/${F_KEYMGR_002_NAME}.json)
set(F_KEYMGR_002_CMD ${TEE_COMMAND} ${F_KEYMGR_002_DEF})
add_test(NAME ${F_KEYMGR_002_NAME} COMMAND ${F_KEYMGR_002_CMD})
set_tests_properties(${F_KEYMGR_002_NAME} PROPERTIES LABELS
		     "${FUNCTIONAL_LABEL};${TEE_LABEL};${KEYMGR_LABEL}")

install(FILES ${SMW_CONFIG_SRC_DIR}/${TEE_CONFIG_FILE}
        DESTINATION ${SMW_TESTS_TARGET_CONFIG_DIR})

FILE(GLOB U_TEE_TEST ${TEST_DEF_SRC_DIR}/U_TEE*.json)
FILE(GLOB F_TEE_TEST ${TEST_DEF_SRC_DIR}/F_TEE*.json)

foreach(file IN LISTS U_TEE_TEST)
	install(FILES ${file} DESTINATION ${SMW_TESTS_TARGET_DEF_DIR})
endforeach()

foreach(file IN LISTS F_TEE_TEST)
	install(FILES ${file} DESTINATION ${SMW_TESTS_TARGET_DEF_DIR})
endforeach()
