set(TEE_CONFIG_FILE tee_config.txt)
set(TEE_COMMAND ${TEST_CMD} ${TEE_CONFIG_FILE})

# Install config file
install(FILES ${SMW_CONFIG_SRC_DIR}/${TEE_CONFIG_FILE}
	DESTINATION ${SMW_TESTS_TARGET_CONFIG_DIR}
	EXCLUDE_FROM_ALL
	COMPONENT ${PROJECT_NAME})

FILE(GLOB TEE_TESTS ${TEST_DEF_SRC_DIR}/*_TEE*.json)

add_and_install_tests("${TEE_TESTS}" "${TEE_COMMAND}")
