/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright 2024 NXP
 */

#ifndef __SMW_NAMES_H__
#define __SMW_NAMES_H__

/**
 * typedef smw_subsystem_t - Secure Subsystem name
 *
 * Values:
 * * SMW_SUBSYSTEM_NAME_NONE: No Secure Subsystem specified
 * * SMW_SUBSYSTEM_NAME_TEE: Trusted Execution Envrionment
 * * SMW_SUBSYSTEM_NAME_SECO: SECO
 * * SMW_SUBSYSTEM_NAME_ELE: Edge Lock Enclave
 * * SMW_SUBSYSTEM_NAME_NB: Number of Secure Subsystems
 */
typedef enum {
	SMW_SUBSYSTEM_NAME_NONE,
	SMW_SUBSYSTEM_NAME_TEE,
	SMW_SUBSYSTEM_NAME_SECO,
	SMW_SUBSYSTEM_NAME_ELE,
	SMW_SUBSYSTEM_NAME_NB
} smw_subsystem_t;

/**
 * typedef smw_operation_t - Security Operation name
 *
 * Values:
 * * SMW_OPERATION_NAME_NONE: No operation specified
 * * SMW_OPERATION_NAME_HASH: Hash a message
 * * SMW_OPERATION_NAME_SIGN: Sign a message
 * * SMW_OPERATION_NAME_VERIFY: Verify the signature of a message
 * * SMW_OPERATION_NAME_RNG: Generate a Random Number
 * * SMW_OPERATION_NAME_CIPHER: Cipher encryption or decryption
 * * SMW_OPERATION_NAME_CIPHER_MULTI_PART: Cipher multi-part encryption or decryption
 * * SMW_OPERATION_NAME_MAC: Generate a Message Authentication Code
 * * SMW_OPERATION_NAME_AEAD: Authenticated Encryption with Associated Data
 * * SMW_OPERATION_NAME_AEAD_MULTI_PART: AEAD multi-part
 * * SMW_OPERATION_NAME_AEAD_UPDATE_AAD: Update AEAD Additional Authenticated Data
 * * SMW_OPERATION_NAME_DEVICE_GET_UUID: Get device UUID
 * * SMW_OPERATION_NAME_DEVICE_ATTESTATION: Attest device
 * * SMW_OPERATION_NAME_DEVICE_LIFECYCLE: Get or set Device lifecycle
 * * SMW_OPERATION_NAME_DEVICE_REPROVISION: Prepare or send a device reprovisioning message
 * * SMW_OPERATION_NAME_GENERATE_KEY: Generate a key
 * * SMW_OPERATION_NAME_DERIVE_KEY: Derive a key
 * * SMW_OPERATION_NAME_UPDATE_KEY: Update a key
 * * SMW_OPERATION_NAME_IMPORT_KEY: Import a key
 * * SMW_OPERATION_NAME_EXPORT_KEY: Export a key
 * * SMW_OPERATION_NAME_DELETE_KEY: Delete a key
 * * SMW_OPERATION_NAME_GET_KEY_LENGTHS: Get key length
 * * SMW_OPERATION_NAME_GET_KEY_ATTRIBUTES: Get key atributes
 * * SMW_OPERATION_NAME_COMMIT_KEY_STORAGE: Commit key storage
 * * SMW_OPERATION_NAME_KEY_ATTESTATION: Attest key
 * * SMW_OPERATION_NAME_STORAGE_STORE: Store data
 * * SMW_OPERATION_NAME_STORAGE_RETRIEVE: Retrieve data
 * * SMW_OPERATION_NAME_STORAGE_DELETE: Delete data
 * * SMW_OPERATION_NAME_STORAGE_IS_DATA_PRESENT: Check if data is present in storage
 * * SMW_OPERATION_NAME_STORAGE_GET_DATA_INFO: Get data info
 * * SMW_OPERATION_NAME_NB: Number of operations
 */
typedef enum {
	SMW_OPERATION_NAME_NONE,
	SMW_OPERATION_NAME_HASH,
	SMW_OPERATION_NAME_SIGN,
	SMW_OPERATION_NAME_VERIFY,
	SMW_OPERATION_NAME_RNG,
	SMW_OPERATION_NAME_CIPHER,
	SMW_OPERATION_NAME_CIPHER_MULTI_PART,
	SMW_OPERATION_NAME_MAC,
	SMW_OPERATION_NAME_AEAD,
	SMW_OPERATION_NAME_AEAD_MULTI_PART,
	SMW_OPERATION_NAME_AEAD_UPDATE_AAD,
	SMW_OPERATION_NAME_DEVICE_GET_UUID,
	SMW_OPERATION_NAME_DEVICE_ATTESTATION,
	SMW_OPERATION_NAME_DEVICE_LIFECYCLE,
	SMW_OPERATION_NAME_DEVICE_REPROVISION,
	SMW_OPERATION_NAME_GENERATE_KEY,
	SMW_OPERATION_NAME_DERIVE_KEY,
	SMW_OPERATION_NAME_UPDATE_KEY,
	SMW_OPERATION_NAME_IMPORT_KEY,
	SMW_OPERATION_NAME_EXPORT_KEY,
	SMW_OPERATION_NAME_DELETE_KEY,
	SMW_OPERATION_NAME_GET_KEY_LENGTHS,
	SMW_OPERATION_NAME_GET_KEY_ATTRIBUTES,
	SMW_OPERATION_NAME_COMMIT_KEY_STORAGE,
	SMW_OPERATION_NAME_KEY_ATTESTATION,
	SMW_OPERATION_NAME_STORAGE_STORE,
	SMW_OPERATION_NAME_STORAGE_RETRIEVE,
	SMW_OPERATION_NAME_STORAGE_DELETE,
	SMW_OPERATION_NAME_STORAGE_IS_DATA_PRESENT,
	SMW_OPERATION_NAME_STORAGE_GET_DATA_INFO,
	SMW_OPERATION_NAME_NB
} smw_operation_t;

/**
 * typedef smw_key_type_t - Key type name
 *
 * Values:
 * * SMW_KEY_TYPE_NAME_NONE: No key type specified
 * * SMW_KEY_TYPE_NAME_SECP_R1: ECC Secp R1 key
 * * SMW_KEY_TYPE_NAME_BRAINPOOL_R1: ECC Brainpool R1 key
 * * SMW_KEY_TYPE_NAME_BRAINPOOL_T1: ECC Brainpool T1 key
 * * SMW_KEY_TYPE_NAME_ED25519: Twisted Edwards 25519 key
 * * SMW_KEY_TYPE_NAME_AES: AES key
 * * SMW_KEY_TYPE_NAME_DES: DES key
 * * SMW_KEY_TYPE_NAME_DES3: Triple DES key
 * * SMW_KEY_TYPE_NAME_DSA_SM2_FP: DSA SM2 key
 * * SMW_KEY_TYPE_NAME_SM4:  SM4 key
 * * SMW_KEY_TYPE_NAME_HMAC: HMAC key
 * * SMW_KEY_TYPE_NAME_RSA: RSA key
 * * SMW_KEY_TYPE_NAME_DH: DH key
 * * SMW_KEY_TYPE_NAME_TLS_MASTER: TLS master key
 * * SMW_KEY_TYPE_NAME_RAW: Raw key
 * * SMW_KEY_TYPE_NAME_NB: Number of key types
 */
typedef enum {
	SMW_KEY_TYPE_NAME_NONE,
	SMW_KEY_TYPE_NAME_SECP_R1,
	SMW_KEY_TYPE_NAME_BRAINPOOL_R1,
	SMW_KEY_TYPE_NAME_BRAINPOOL_T1,
	SMW_KEY_TYPE_NAME_ED25519,
	SMW_KEY_TYPE_NAME_AES,
	SMW_KEY_TYPE_NAME_DES,
	SMW_KEY_TYPE_NAME_DES3,
	SMW_KEY_TYPE_NAME_DSA_SM2_FP,
	SMW_KEY_TYPE_NAME_SM4,
	SMW_KEY_TYPE_NAME_HMAC,
	SMW_KEY_TYPE_NAME_RSA,
	SMW_KEY_TYPE_NAME_DH,
	SMW_KEY_TYPE_NAME_TLS_MASTER,
	SMW_KEY_TYPE_NAME_RAW,
	SMW_KEY_TYPE_NAME_GENERIC_SECRET,
	SMW_KEY_TYPE_NAME_NB
} smw_key_type_t;

#endif /* __SMW_NAMES_H__ */
