/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright 2023-2024, 2026 NXP
 */

#ifndef __SMW_CRYPTO_AEAD_H__
#define __SMW_CRYPTO_AEAD_H__

/**
 * struct smw_aead_init_args - AEAD initialization arguments
 * @version: [in] Version of this structure.
 * @subsystem_name: [in] Secure Subsystem name. See &typedef smw_subsystem_t
 * @key_desc: [in] Pointer to a key descriptor object.
 *            See &struct smw_key_descriptor
 * @mode_name: [in] AEAD mode name. See &typedef smw_aead_mode_t
 * @op_type_name: [in] AEAD operation name. See &typedef smw_aead_op_type_t
 * @user_iv: [in] Pointer to user initialization vector.
 * @user_iv_length: [in] Length in bytes of the user IV buffer.
 * @iv_length: [in] Length in bytes of the requested IV buffer.
 * @aad_length: [in] Length in bytes of the additional authentication data.
 * @tag_length: [in] Length in bytes of the tag.
 * @plaintext_length: [in] Length in bytes of the data to encrypt.
 * @context: [in/out] Pointer the multipart operation context.
 *
 * Field @context:\
 *
 *  - Is used only for multi-part operations.
 *  - Must be allocated by smw_allocate_context().
 *  - Is initialized when initialization operation returned successfully.
 *
 * The @subsystem_name designates the Secure Subsystem to be used.
 * If this field is :ref:`SMW_SUBSYSTEM_NAME_NONE <smw_subsystem_t>`,
 * the Secure Subsystem is the default one defined in the library configuration
 * or it's the one handling the key is key identifier is defined.
 *
 * If subsystem offers the capability to generate partial or complete IV:\
 *
 *  - To request the full generation of the IV, the @user_iv_length must be 0.
 *  - To request the partial generation of the IV, the @user_iv_length must be
 *    less than subsystem IV maximum length (usually 12 bytes) and @iv_length
 *    must be the requested length to be generated by the subsystem.
 *
 * Otherwise, if @user_iv_length is set to the maximum IV size supported by
 * the subsystem, @iv_length is not taking into consideration. Please refer
 * to the AEAD description of the :ref:`subsystems-capabilities`.
 */
struct smw_aead_init_args {
	unsigned char version;
	smw_subsystem_t subsystem_name;
	struct smw_key_descriptor *key_desc;
	smw_aead_mode_t mode_name;
	smw_aead_op_type_t op_type_name;
	unsigned char *user_iv;
	unsigned int user_iv_length;
	unsigned int iv_length;
	unsigned int aad_length;
	unsigned int tag_length;
	unsigned int plaintext_length;
	struct smw_op_context *context;
};

/**
 * struct smw_aead_data_args - AEAD data arguments
 * @version: [in] Version of this structure.
 * @context: [in/out] Pointer the multipart operation context updated by
 *           smw_aead_init(), smw_aead_update() or smw_aead_update_aad().
 * @input: [in] Pointer to input data buffer to be encrypted or decrypted
 * @input_length: [in] Length in bytes of the input data buffer.
 * @output: [out] Pointer to output buffer.
 * @output_length: [out] Length in bytes of the output buffer.
 *
 * Field @context:\
 *
 *  - Is used only for multi-part operations.
 *  - Is updated when update operation returned successfully.
 *  - Is deleted when final operation returned except under conditions detailed
 *    in the smw_aead_final() function description.
 */
struct smw_aead_data_args {
	unsigned char version;
	struct smw_op_context *context;
	unsigned char *input;
	unsigned int input_length;
	unsigned char *output;
	unsigned int output_length;
};

/**
 * struct smw_aead_aad_args - Authentication Encryption AAD arguments
 * @version: [in] Version of this structure.
 * @data: [in] Pointer to additional authentication data.
 * @data_length: [in] Length in bytes of the additional authentication data.
 * @context: [in/out] Pointer the multipart operation context updated by
 *           smw_aead_init(), smw_aead_update() or smw_aead_update_aad().
 *
 * Field @context:\
 *
 *  - Is used only for multi-part operations.
 *  - Is updated when update operation returned successfully.
 */
struct smw_aead_aad_args {
	unsigned char version;
	unsigned char *data;
	unsigned int data_length;
	struct smw_op_context *context;
};

/**
 * struct smw_aead_final_args - AEAD final arguments
 * @version: [in] Version of this structure.
 * @data: [in] Pointer to AEAD data arguments. See &struct smw_aead_data_args
 * @op_type_name: [in] AEAD operation name. See &typedef smw_aead_op_type_t
 * @tag:
 *  - [in] Pointer to tag buffer to be compared.
 *  - [out] Pointer to tag buffer generated.
 * @tag_length:
 *  - [in] Length in bytes of the tag buffer.
 *  - [out] Length in bytes of the tag buffer generated.
 * @output_iv_length:
 *  - [in] Length in bytes of output IV buffer.
 *  - [out] Length in bytes of output IV generated.
 * @output_iv: [out] Pointer to output IV buffer
 *
 * The @output_iv buffer should be allocated by the caller application for
 * encryption operation.
 * Upon successful encryption operation, @output_iv will contain the IV
 * used by subsystem during operation.
 *
 * Fields @output_iv_length and @output_iv are ignored for decryption operation.
 */
struct smw_aead_final_args {
	unsigned char version;
	struct smw_aead_data_args *data;
	smw_aead_op_type_t op_type_name;
	unsigned char *tag;
	unsigned int tag_length;
	unsigned int output_iv_length;
	unsigned char *output_iv;
};

/**
 * struct smw_aead_args - AEAD one-shot arguments
 * @version: [in] Version of this structure.
 * @aad: [in] Pointer to AAD arguments. See &struct smw_aead_aad_args
 * @init: [in/out] Pointer to initialization arguments.
 *         See &struct smw_aead_init_args
 * @final: [in/out] Pointer to final arguments. See &struct smw_aead_final_args
 *
 * This structure is defined with the multi-part operation but:\
 *
 *   - Field @context present in @init, @aad and @final is ignored.
 *   - Field @op_type_name present in @final is ignored, only the one in @init
 *     is used.
 */
struct smw_aead_args {
	unsigned char version;
	struct smw_aead_aad_args *aad;
	struct smw_aead_init_args *init;
	struct smw_aead_final_args *final;
};

/**
 * smw_aead() - AEAD encryption or decryption.
 * @args: Pointer to the structure that contains the AEAD one-shot arguments.
 *
 * This function executes one-shot AEAD encryption or decryption operation
 * using a key present in the Secure Subsystem storage identified by the key
 * descriptor identifier or a plaintext key value filled in the key descriptor
 * private data buffer.
 *
 * Encryption operation:\
 *
 *  - This function encrypts a message and computes the tag.
 *  - If the @args->final->tag field is set, the computed tag will be stored
 *    in the dedicated @args->final->tag field. The output buffer should be
 *    large enough to contain the computed ciphertext.
 *  - If the @args->final->tag field is not set, @args->final->data->output
 *    field will contain the ciphertext followed by the tag. The output buffer
 *    should be large enough to contain concatenated value.
 *
 * Decryption operation:\
 *
 *   - This function authenticates and decrypts the ciphertext.
 *   - If the @args->final->tag field is not set, the @args->final->data->input
 *     should contain the ciphertext followed by the tag.
 *   - If the computed tag does not match the supplied tag, the operation
 *     will be terminated.
 *   - The @args->final->data->output buffer should be large enough to contain
 *     the computed plaintext.
 *
 * To query the required AEAD encryption or decryption final result output
 * buffer length, set @args->final->data->output to NULL. The function will
 * then set the required output buffer length in
 * @args->final->data->output_length and return SMW_STATUS_OK. In case of
 * encryption, the @args->tag_length and @args->output_iv_length are also set
 * with expected values.
 *
 * On operation completion, the @args->final->data->output_length is updated
 * to the correct value when:\
 *
 *  - Output length is bigger than expected. In this case, operation succeeds.
 *  - Output length is shorter than expected. In this case, operation fails and
 *    returns SMW_STATUS_OUTPUT_TOO_SHORT.
 *  - In the above mentioned two scenarios, if the operation is encryption, the
 *    function also updates the required tag buffer length
 *    @args->final->tag_length and output IV length
 *    @args->final->output_iv_length.
 *
 * Additionally, on encryption operation completion:\
 *
 *   - The tag length @args->final->tag_length is updated with the generated
 *     tag value length even if the tag value is concatenated in the output
 *     resulting buffer.
 *   - The output IV length @args->final->output_iv contains the IV used during
 *     the operation and the @args->final->ouput_iv_length is updated with the
 *     IV length.
 *
 * Return:
 *  - SMW_STATUS_OK:
 *      Operation succeeded.
 *  - SMW_STATUS_INVALID_PARAM:
 *      - @args is NULL.
 *      - @args->init is NULL.
 *      - @args->final is NULL.
 *      - @args->final->data is NULL.
 *      - @args->final->data->input is NULL.
 *      - @args->final->data->input_length is 0.
 *      - @args->final->data->output is NULL and
 *        @args->final->data->output_length is not 0.
 *      - @args->final->output_iv is NULL, when encryption operation.
 *      - @args->init->key_descriptor is NULL.
 *      - @args->init->mode is SMW_AEAD_MODE_NAME_NONE.
 *      - @args->init->op_type_name is SMW_AEAD_OP_TYPE_NAME_NONE.
 *      - @args->init->user_iv is NULL and @args->init->user_iv_length is not 0.
 *      - If tag length is not given in one of @init or @final structure.
 *      - If key descriptor is not correctly defined. No key id and no key
 *        buffer.
 *      - In case of using plaintext key, private buffer is NULL or length is 0.
 *      - Additional invalid parameters returned by the subsystem.
 *  - Other error code from &enum smw_status_code
 */
enum smw_status_code smw_aead(struct smw_aead_args *args);

/**
 * smw_aead_init() - AEAD multi-part initialization.
 * @args: Pointer to the structure that contains the AEAD initialization
 * arguments.
 *
 * This function initializes AEAD multi-part encryption or decryption
 * operation using a key present in the Secure Subsystem storage identified
 * by the key descriptor identifier or a plaintext key value filled in the key
 * descriptor private data buffer.
 *
 * The operation context must be allocated using smw_allocate_context() API
 * prior to invoking this API.
 *
 * The **context** remains valid after this operation if return error code is:\
 *
 *  - SMW_STATUS_OK
 *  - SMW_STATUS_INVALID_PARAM
 *  - SMW_STATUS_VERSION_NOT_SUPPORTED
 *  - SMW_STATUS_UNKNOWN_SUBSYSTEM_NAME
 *  - SMW_STATUS_UNKNOWN_MODE_NAME
 *  - SMW_STATUS_UNKNOWN_OP_TYPE_NAME
 *  - SMW_STATUS_OPERATION_ALREADY_INIT
 *  - SMW_STATUS_UNKNOWN_ID
 *
 * Otherwise, the **context** is freed and becomes invalid, @args->context is
 * set to NULL.
 *
 * Return:
 *  - SMW_STATUS_OK:
 *      Operation succeeded.
 *  - SMW_STATUS_INVALID_PARAM:
 *      - @args is NULL.
 *      - @args->key_descriptor is NULL.
 *      - @args->context is NULL.
 *      - @args->mode is SMW_AEAD_MODE_NAME_NONE.
 *      - @args->op_type_name is SMW_AEAD_OP_TYPE_NAME_NONE.
 *      - @args->user_iv is NULL and @args->user_iv_length is not 0.
 *      - @args->plaintext_length is 0 for the AEAD CCM mode.
 *      - @args->tag_length is 0.
 *      - If key descriptor is not correctly defined. No key id and no key
 *        buffer.
 *      - In case of using plaintext key, private buffer is NULL or length is 0.
 *      - Additional invalid parameters returned by the subsystem.
 *  - Other error code from &enum smw_status_code
 */
enum smw_status_code smw_aead_init(struct smw_aead_init_args *args);

/**
 * smw_aead_update_aad() - Update AEAD additional authenticated data.
 * @args: Pointer to the structure that contains the AEAD additional data
 *        arguments.
 *
 * This function can be called multiple time while the update data
 * (to encrypt or to decrypt) step is not called.
 *
 * The context used must be initialized by the AEAD multi-part initialization
 * smw_aead_init() API or updated by a previous smw_aead_update_aad() call.
 *
 * The **context** remains valid after this operation if return error code is:\
 *
 *  - SMW_STATUS_OK
 *  - SMW_STATUS_INVALID_PARAM
 *  - SMW_STATUS_VERSION_NOT_SUPPORTED
 *  - SMW_STATUS_UNKNOWN_SUBSYSTEM_NAME
 *
 * Otherwise, the **context** is freed and becomes invalid, @args->context is
 * set to NULL.
 *
 * Return:
 *  - SMW_STATUS_OK:
 *      Operation succeeded.
 *  - SMW_STATUS_INVALID_PARAM:
 *      - @args is NULL.
 *      - @args->context is NULL.
 *      - @args->data is NULL.
 *      - @args->data_length is 0.
 *      - Additional invalid parameters returned by the subsystem.
 *  - Other error code from &enum smw_status_code
 */
enum smw_status_code smw_aead_update_aad(struct smw_aead_aad_args *args);

/**
 * smw_aead_update() - AEAD multi-part update.
 * @args: Pointer to the structure that contains the AEAD multi-part data
 *        arguments.
 *
 * This function executes a AEAD multi-part encryption or decryption update
 * operation.
 *
 * The context used must be initialized by the AEAD multi-part initialization
 * smw_aead_init() API or updated by a previous smw_aead_update_aad() or
 * smw_aead_update() call.
 *
 * To query the required AEAD encryption or decryption update result output
 * buffer length, set @args->output to NULL. The function will then set the
 * required output buffer length in @args->output_length and return
 * SMW_STATUS_OK.
 *
 * On operation completion, the @args->output_length is updated to the
 * correct value when:\
 *
 *  - Output buffer length is bigger than expected. In this case, operation
 *    succeeds.
 *  - Output buffer length is shorter than expected. In this case, operation
 *    fails and returns SMW_STATUS_OUTPUT_TOO_SHORT.
 *
 * The **context** remains valid after this operation if return error code is:\
 *
 *  - SMW_STATUS_OK
 *  - SMW_STATUS_INVALID_PARAM
 *  - SMW_STATUS_VERSION_NOT_SUPPORTED
 *  - SMW_STATUS_UNKNOWN_SUBSYSTEM_NAME
 *  - SMW_STATUS_OUTPUT_TOO_SHORT
 *
 * Otherwise, the **context** is freed and becomes invalid, @args->context is
 * set to NULL.
 *
 * Return:
 *  - SMW_STATUS_OK:
 *      Operation succeeded.
 *  - SMW_STATUS_INVALID_PARAM:
 *      - @args is NULL.
 *      - @args->context is NULL.
 *      - @args->input is NULL.
 *      - @args->input_length is 0.
 *      - @args->output is not NULL and @args->output_length is 0.
 *      - Additional invalid parameters returned by the subsystem.
 *  - Other error code from &enum smw_status_code
 */
enum smw_status_code smw_aead_update(struct smw_aead_data_args *args);

/**
 * smw_aead_final() - AEAD multi-part encryption/decryption final.
 * @args: Pointer to the structure that contains the AEAD multi-part final
 *        arguments.
 *
 * This function completes the active AEAD multi-part encryption/decryption
 * operation.
 *
 * The context used must be initialized by the AEAD multi-part initialization
 * smw_aead_init() API or updated by a previous smw_aead_update() call.
 *
 * Encryption operation:\
 *
 *  - This function finalize the message encrytion and computes the tag.
 *  - If the @args->tag field is set, the computed tag will be stored
 *    in the dedicated @args->tag field. The output buffer should be
 *    large enough to contain the computed ciphertext.
 *  - If the @args->tag field is not set, @args->data->output
 *    field will contain the ciphertext followed by the tag. The output buffer
 *    should be large enough to contain concatenated value.
 *
 * Decryption operation:\
 *
 *   - This function finalizes authenticating and decrypting the ciphertext.
 *   - If the @args->tag field is not set, the @args->data->input
 *     should contain the ciphertext followed by the tag.
 *   - If the computed tag does not match the supplied tag, the operation
 *     will be terminated.
 *   - The @args->data->output buffer should be large enough to contain
 *     the computed plaintext.
 *
 * To query the required AEAD encryption or decryption final result output
 * buffer length, set @args->data->output to NULL. The function will
 * then set the required output buffer length in @args->data->output_length
 * and return SMW_STATUS_OK. In case of encryption, the @args->tag_length and
 * @args->output_iv_length are also set with expected values.
 *
 * On operation completion, the @args->data->output_length is updated
 * to the correct value when:\
 *
 *  - Output length is bigger than expected. In this case, operation succeeds.
 *  - Output length is shorter than expected. In this case, operation fails and
 *    returns SMW_STATUS_OUTPUT_TOO_SHORT.
 *  - In the above mentioned two scenarios, if the operation is encryption, the
 *    function also updates the required tag buffer length
 *    @args->tag_length and output IV length @args->output_iv_length.
 *
 * Additionally, on encryption operation completion:\
 *
 *   - The tag length @args->tag_length is updated with the generated
 *     tag value length even if the tag value is concatenated in the output
 *     resulting buffer.
 *   - The output IV length @args->output_iv contains the IV used during
 *     the operation and the @args->ouput_iv_length is updated with the
 *     IV length.
 *
 * The **context** remains valid after this operation if return error code is:\
 *
 *  - SMW_STATUS_OK in case output buffer is set to NULL.
 *  - SMW_STATUS_INVALID_PARAM
 *  - SMW_STATUS_VERSION_NOT_SUPPORTED
 *  - SMW_STATUS_UNKNOWN_SUBSYSTEM_NAME
 *  - SMW_STATUS_OUTPUT_TOO_SHORT
 *  - SMW_STATUS_UNKNOWN_OP_TYPE_NAME
 *
 * Otherwise, the **context** is freed and becomes invalid, @args->context is
 * set to NULL.
 *
 * Return:
 *  - SMW_STATUS_OK:
 *      Operation succeeded.
 *  - SMW_STATUS_INVALID_PARAM:
 *      - @args is NULL.
 *      - @args->data is NULL.
 *      - @args->data->context is NULL.
 *      - @args->data->input is not NULL and @args->data->input_length is 0.
 *      - @args->data->output is not NULL and @args->output_length is 0.
 *      - @args->tag_length is 0.
 *      - @args->final->output_iv is NULL, when encryption operation.
 *      - Additional invalid parameters returned by the subsystem.
 *  - Other error code from &enum smw_status_code
 */
enum smw_status_code smw_aead_final(struct smw_aead_final_args *args);

#endif /* __SMW_CRYPTO_AEAD_H__ */
