// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2025 NXP
 */

#include <stdlib.h>

#include "util.h"
#include "util_asymm_encryption.h"

/**
 * struct asymm_encryption_data - Data of output linked list node.
 * @output: Buffer containing the output generated by SMW.
 * @output_length: Length of the output.
 */
struct asymm_encryption_data {
	unsigned char *output;
	unsigned int output_length;
};

static void asymm_enc_free_data(void *data)
{
	struct asymm_encryption_data *asymm_encryption_data = data;

	if (asymm_encryption_data) {
		if (asymm_encryption_data->output)
			free(asymm_encryption_data->output);

		free(asymm_encryption_data);
	}
}

int util_asymm_enc_init(struct llist **list)
{
	if (!list)
		return ERR_CODE(BAD_ARGS);

	return util_list_init(list, asymm_enc_free_data, LIST_ID_TYPE_UINT);
}

int util_asymm_enc_add_node(struct llist *list, unsigned int id,
			    unsigned char *output, unsigned int output_length)
{
	int res = ERR_CODE(BAD_ARGS);
	struct asymm_encryption_data *data;

	if (!list)
		return res;

	data = malloc(sizeof(*data));
	if (!data) {
		DBG_PRINT_ALLOC_FAILURE();
		return ERR_CODE(INTERNAL_OUT_OF_MEMORY);
	}

	data->output = output;
	data->output_length = output_length;

	res = util_list_add_node(list, id, data);

	if (res != ERR_CODE(PASSED) && data)
		free(data);

	return res;
}

int util_asymm_enc_find_node(struct llist *list, unsigned int id,
			     unsigned char **output,
			     unsigned int *output_length)
{
	int res = ERR_CODE(BAD_ARGS);
	struct asymm_encryption_data *data = NULL;

	if (!list || !output || !output_length)
		return res;

	res = util_list_find_node(list, id, (void **)&data);
	if (res == ERR_CODE(PASSED) && !data)
		return ERR_CODE(FAILED);

	if (res == ERR_CODE(PASSED)) {
		*output = data->output;
		*output_length = data->output_length;
	}

	return res;
}
