#
# This file contains the configuration of the SMW library.
# It must be installed in the system folder `/etc/opt/smw/smw.conf`
# All sections are not mandatory.
#
[setup]
# SMW configuration file describing the subsystem(s) operations
# smw_config_file=[path/to/file]

# SMW object database containing all known objects
# database=[path/to/file]
database=/usr/share/smw/smw_objects_database.dat

[TEE]
# OPTEE TA UUID to be loaded if subsystem used.
# ta_uuid must be defined.

[SECO]
# SECO subsystem NVM Secure Storage configuration if subsystem used.
# Following 3 items must be defined
# id=
# nonce=
# replay=

[ELE]
# ELE subsystem NVM Secure Storage configuration if subsystem used.
# Following 3 items must be defined
# id=
# nonce=
# shared=
