#
# This file contains the configuration of the SMW library.
# It must be installed in the system folder `/etc/opt/smw/smw.conf`
# All sections are not mandatory.
#
[setup]
# SMW configuration file describing the subsystem(s) operations
# smw_config_file=[path/to/file]

# SMW object database containing all known objects
# database=[path/to/file]

[TEE]
# OPTEE TA UUID to be loaded if subsystem used.
# ta_uuid must be defined.
# e.g. ta_uuid=11b5c4aa-6d20-11ea-bc55-0242ac130003

[SECO]
# SECO subsystem NVM Secure Storage configuration if subsystem used.
# Following 3 items must be defined
# id=
# nonce=
# replay=
#
# e.g.:
# id=0x534d5754
# nonce=0x444546
# replay=1000

[ELE]
# ELE subsystem NVM Secure Storage configuration if subsystem used.
# Following 2 items must be defined
# id=
# nonce=
#
# e.g.:
# id=0x534d5754
# nonce=0x444546
