/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright 2024-2025 NXP
 */

#ifndef __CONFIG_IDS_H__
#define __CONFIG_IDS_H__

/*
 * Ordering must be the same for internal values and public values.
 * This way the offset between the internal values and the public values
 * can be used for conversion, and no conversion table is required.
 *
 * The offset between the internal values and the public values is
 * given by the first public value.
 */

enum smw_config_key_type_id {
	SMW_CONFIG_KEY_TYPE_ID_SECP_R1,
	SMW_CONFIG_KEY_TYPE_ID_BRAINPOOL_R1,
	SMW_CONFIG_KEY_TYPE_ID_BRAINPOOL_T1,
	SMW_CONFIG_KEY_TYPE_ID_ED25519,
	SMW_CONFIG_KEY_TYPE_ID_AES,
	SMW_CONFIG_KEY_TYPE_ID_DES,
	SMW_CONFIG_KEY_TYPE_ID_DES3,
	SMW_CONFIG_KEY_TYPE_ID_DSA_SM2_FP,
	SMW_CONFIG_KEY_TYPE_ID_SM4,
	SMW_CONFIG_KEY_TYPE_ID_HMAC,
	SMW_CONFIG_KEY_TYPE_ID_RSA,
	SMW_CONFIG_KEY_TYPE_ID_DH,
	SMW_CONFIG_KEY_TYPE_ID_TLS_MASTER,
	SMW_CONFIG_KEY_TYPE_ID_RAW,
	SMW_CONFIG_KEY_TYPE_ID_DERIVE,
	SMW_CONFIG_KEY_TYPE_ID_HKDF_IKM,
	SMW_CONFIG_KEY_TYPE_ID_X25519,
	SMW_CONFIG_KEY_TYPE_ID_NB,
	SMW_CONFIG_KEY_TYPE_ID_INVALID
};

enum smw_config_hash_algo_id {
	SMW_CONFIG_HASH_ALGO_ID_MD5,
	SMW_CONFIG_HASH_ALGO_ID_SHA1,
	SMW_CONFIG_HASH_ALGO_ID_SHA224,
	SMW_CONFIG_HASH_ALGO_ID_SHA256,
	SMW_CONFIG_HASH_ALGO_ID_SHA384,
	SMW_CONFIG_HASH_ALGO_ID_SHA512,
	SMW_CONFIG_HASH_ALGO_ID_SHA3_224,
	SMW_CONFIG_HASH_ALGO_ID_SHA3_256,
	SMW_CONFIG_HASH_ALGO_ID_SHA3_384,
	SMW_CONFIG_HASH_ALGO_ID_SHA3_512,
	SMW_CONFIG_HASH_ALGO_ID_SM3,
	SMW_CONFIG_HASH_ALGO_ID_NB,
	SMW_CONFIG_HASH_ALGO_ID_INVALID
};

enum smw_config_mac_algo_id {
	SMW_CONFIG_MAC_ALGO_ID_CMAC,
	SMW_CONFIG_MAC_ALGO_ID_CMAC_TRUNCATED,
	SMW_CONFIG_MAC_ALGO_ID_HMAC,
	SMW_CONFIG_MAC_ALGO_ID_HMAC_TRUNCATED,
	SMW_CONFIG_MAC_ALGO_ID_NB,
	SMW_CONFIG_MAC_ALGO_ID_INVALID
};

enum smw_config_mac_op_type_id {
	SMW_CONFIG_MAC_OP_ID_COMPUTE,
	SMW_CONFIG_MAC_OP_ID_VERIFY,
	SMW_CONFIG_MAC_OP_ID_NB,
	SMW_CONFIG_MAC_OP_ID_INVALID
};

enum smw_config_sign_algo_id {
	SMW_CONFIG_SIGN_ALGO_ID_DEFAULT,
	SMW_CONFIG_SIGN_ALGO_ID_ECDSA,
	SMW_CONFIG_SIGN_ALGO_ID_EDDSA,
	SMW_CONFIG_SIGN_ALGO_ID_DSA,
	SMW_CONFIG_SIGN_ALGO_ID_RSA,
	SMW_CONFIG_SIGN_ALGO_ID_TLS_1_2,
	SMW_CONFIG_SIGN_ALGO_ID_NB,
	SMW_CONFIG_SIGN_ALGO_ID_INVALID
};

enum smw_config_sign_type_id {
	SMW_CONFIG_SIGN_TYPE_ID_DEFAULT,
	SMW_CONFIG_SIGN_TYPE_ID_PKCS1_1_5,
	SMW_CONFIG_SIGN_TYPE_ID_PSS,
	SMW_CONFIG_SIGN_TYPE_ID_CLIENT,
	SMW_CONFIG_SIGN_TYPE_ID_SERVER,
	SMW_CONFIG_SIGN_TYPE_ID_CMAC,
	SMW_CONFIG_SIGN_TYPE_ID_PURE_EDDSA,
	SMW_CONFIG_SIGN_TYPE_ID_EDDSA_PH,
	SMW_CONFIG_SIGN_TYPE_ID_EDDSA_CTX,
	SMW_CONFIG_SIGN_TYPE_ID_NB,
	SMW_CONFIG_SIGN_TYPE_ID_INVALID
};

enum smw_config_cipher_op_type_id {
	SMW_CONFIG_CIPHER_OP_TYPE_ID_ENCRYPT,
	SMW_CONFIG_CIPHER_OP_TYPE_ID_DECRYPT,
	SMW_CONFIG_CIPHER_OP_TYPE_ID_NB,
	SMW_CONFIG_CIPHER_OP_TYPE_ID_INVALID
};

enum smw_config_cipher_mode_id {
	SMW_CONFIG_CIPHER_MODE_ID_CBC,
	SMW_CONFIG_CIPHER_MODE_ID_CFB,
	SMW_CONFIG_CIPHER_MODE_ID_CTR,
	SMW_CONFIG_CIPHER_MODE_ID_CTS,
	SMW_CONFIG_CIPHER_MODE_ID_ECB,
	SMW_CONFIG_CIPHER_MODE_ID_XTS,
	SMW_CONFIG_CIPHER_MODE_ID_NB,
	SMW_CONFIG_CIPHER_MODE_ID_INVALID
};

enum smw_config_kdf_id {
	SMW_CONFIG_KDF_ID_HKDF,
	SMW_CONFIG_KDF_ID_HKDF_EXTRACT,
	SMW_CONFIG_KDF_ID_HKDF_EXPAND,
	SMW_CONFIG_KDF_ID_TLS12_KEY_EXCHANGE,
	SMW_CONFIG_KDF_ID_ECDH,
	SMW_CONFIG_KDF_ID_TLS12_OP_KEY_EXCHANGE,
	SMW_CONFIG_KDF_ID_TLS13_KEY_EXCHANGE,
	SMW_CONFIG_KDF_ID_NB,
	SMW_CONFIG_KDF_ID_INVALID
};

enum smw_config_aead_mode_id {
	SMW_CONFIG_AEAD_MODE_ID_CCM,
	SMW_CONFIG_AEAD_MODE_ID_GCM,
	SMW_CONFIG_AEAD_MODE_ID_CHACHA20_POLY1305,
	SMW_CONFIG_AEAD_MODE_ID_NB,
	SMW_CONFIG_AEAD_MODE_ID_INVALID
};

enum smw_config_aead_op_type_id {
	SMW_CONFIG_AEAD_OP_TYPE_ID_ENCRYPT,
	SMW_CONFIG_AEAD_OP_TYPE_ID_DECRYPT,
	SMW_CONFIG_AEAD_OP_TYPE_ID_NB,
	SMW_CONFIG_AEAD_OP_TYPE_ID_INVALID
};

enum smw_config_asymm_enc_mode_id {
	SMW_CONFIG_ASYMM_ENC_MODE_ID_PKCS1_1_5,
	SMW_CONFIG_ASYMM_ENC_MODE_ID_OAEP,
	SMW_CONFIG_ASYMM_ENC_MODE_ID_NO_PAD,
	SMW_CONFIG_ASYMM_ENC_MODE_ID_NB,
	SMW_CONFIG_ASYMM_ENC_MODE_ID_INVALID
};

enum smw_config_asymm_enc_algo_id {
	SMW_CONFIG_ASYMM_ENC_ALGO_ID_RSA,
	SMW_CONFIG_ASYMM_ENC_ALGO_ID_NB,
	SMW_CONFIG_ASYMM_ENC_ALGO_ID_INVALID
};

#endif /* __CONFIG_IDS_H__ */
