/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright 2024 NXP
 */

#ifndef __LIFECYCLE_H___
#define __LIFECYCLE_H___

enum smw_lifecycle_id {
	SMW_LIFECYCLE_ID_CURRENT,
	SMW_LIFECYCLE_ID_OPEN,
	SMW_LIFECYCLE_ID_CLOSED,
	SMW_LIFECYCLE_ID_CLOSED_LOCKED,
	SMW_LIFECYCLE_ID_OEM_RETURN,
	SMW_LIFECYCLE_ID_NXP_RETURN,
	SMW_LIFECYCLE_ID_NB,
	SMW_LIFECYCLE_ID_INVALID
};

#endif /* __LIFECYCLE_H___ */
