/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright 2022-2023 NXP
 */

#ifndef __TLV_STRINGS_H__
#define __TLV_STRINGS_H__

#define PERSISTENT_STR	   "PERSISTENT"
#define RSA_PUB_EXP_STR	   "RSA_PUB_EXP"
#define FLUSH_KEY_STR	   "FLUSH_KEY"
#define POLICY_STR	   "POLICY"
#define USAGE_STR	   "USAGE"
#define EXPORT_STR	   "EXPORT"
#define COPY_STR	   "COPY"
#define ENCRYPT_STR	   "ENCRYPT"
#define DECRYPT_STR	   "DECRYPT"
#define SIGN_MESSAGE_STR   "SIGN_MESSAGE"
#define VERIFY_MESSAGE_STR "VERIFY_MESSAGE"
#define SIGN_HASH_STR	   "SIGN_HASH"
#define VERIFY_HASH_STR	   "VERIFY_HASH"
#define DERIVE_STR	   "DERIVE"
#define ALGO_STR	   "ALGO"
#define HASH_STR	   "HASH"
#define KDF_STR		   "KDF"
#define LENGTH_STR	   "LENGTH"
#define MIN_LENGTH_STR	   "MIN_LENGTH"
#define LIFECYCLE_STR	   "LIFECYCLE"
#define STORAGE_ID_STR	   "STORAGE_ID"

#define LC_OPEN_STR	     "OPEN"
#define LC_CLOSED_STR	     "CLOSED"
#define LC_CLOSED_LOCKED_STR "CLOSED_LOCKED"
#define LC_CURRENT_STR	     "CURRENT"
#define LC_OEM_RETURN_STR    "OEM_RETURN"
#define LC_NXP_RETURN_STR    "NXP_RETURN"

#define READ_ONLY_STR  "READ_ONLY"
#define READ_ONCE_STR  "READ_ONCE"
#define WRITE_ONLY_STR "WRITE_ONLY"

#define ANY_STR			    "ANY"
#define ALL_AEAD_STR		    "ALL_AEAD"
#define ALL_CIPHER_STR		    "ALL_CIPHER"
#define HMAC_STR		    "HMAC"
#define CBC_MAC_STR		    "CBC_MAC"
#define CMAC_STR		    "CMAC"
#define STREAM_CIPHER_STR	    "STREAM_CIPHER"
#define CTR_STR			    "CTR"
#define CFB_STR			    "CFB"
#define OFB_STR			    "OFB"
#define XTS_STR			    "XTS"
#define ECB_NO_PADDING_STR	    "ECB_NO_PADDING"
#define CBC_NO_PADDING_STR	    "CBC_NO_PADDING"
#define CBC_PKCS7_STR		    "CBC_PKCS7"
#define CCM_STR			    "CCM"
#define GCM_STR			    "GCM"
#define CHACHA20_POLY1305_STR	    "CHACHA20_POLY1305"
#define HKDF_STR		    "HKDF"
#define TLS12_PRF_STR		    "TLS12_PRF"
#define TLS12_PSK_TO_MS_STR	    "TLS12_PSK_TO_MS"
#define PBKDF2_HMAC_STR		    "PBKDF2_HMAC"
#define PBKDF2_AES_CMAC_PRF_128_STR "PBKDF2_AES_CMAC_PRF_128"
#define RSA_PKCS1V15_STR	    "RSA_PKCS1V15"
#define RSA_PSS_STR		    "RSA_PSS"
#define RSA_PSS_ANY_SALT_STR	    "RSA_PSS_ANY_SALT"
#define ECDSA_STR		    "ECDSA"
#define DETERMINISTIC_ECDSA_STR	    "DETERMINISTIC_ECDSA"
#define PURE_EDDSA_STR		    "PURE_EDDSA"
#define ED25519PH_STR		    "ED25519PH"
#define ED448PH_STR		    "ED448PH"
#define RSA_PKCS1V15_CRYPT_STR	    "RSA_PKCS1V15_CRYPT"
#define RSA_OAEP_STR		    "RSA_OAEP"
#define ECDH_STR		    "ECDH"
#define FFDH_STR		    "FFDH"
#define MD2_STR			    "MD2"
#define MD4_STR			    "MD4"
#define MD5_STR			    "MD5"
#define RIPEMD160_STR		    "RIPEMD160"
#define SHA_1_STR		    "SHA1"
#define SHA_224_STR		    "SHA224"
#define SHA_256_STR		    "SHA256"
#define SHA_384_STR		    "SHA384"
#define SHA_512_STR		    "SHA512"
#define SHA_512_224_STR		    "SHA512_224"
#define SHA_512_256_STR		    "SHA512_256"
#define SHA3_224_STR		    "SHA3_224"
#define SHA3_256_STR		    "SHA3_256"
#define SHA3_384_STR		    "SHA3_384"
#define SHA3_512_STR		    "SHA3_512"
#define SHAKE256_512_STR	    "SHAKE256_512"
#define SM3_STR			    "SM3"

#endif /* __TLV_STRINGS_H__ */
