#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 NXP

"""
Script to generate PSA error handler from public/psa/error.h
This ensures the error descriptions stay in sync with the status codes.
"""

import re
import sys
from pathlib import Path

def parse_psa_error_header(header_path):
    """Parse psa/error.h and extract error codes with descriptions."""

    with open(header_path, 'r') as f:
        content = f.read()

    typedef_pattern = r'/\*\*\s*\n\s*\* typedef psa_status_t.*?\*/'
    typedef_match = re.search(typedef_pattern, content, re.DOTALL)

    if not typedef_match:
        print("ERROR: Could not find typedef psa_status_t documentation", file=sys.stderr)
        sys.exit(1)

    typedef_doc = typedef_match.group(0)

    error_pattern = r'\*\s+(PSA_(?:SUCCESS|ERROR_\w+)):\s*\n\s*\*\s+([^\n]+(?:\n\s*\*\s+[^\n*]+)*)'

    status_descriptions = {}
    for match in re.finditer(error_pattern, typedef_doc):
        error_code = match.group(1)
        description = match.group(2)

        description = re.sub(r'\n\s*\*\s+', ' ', description)
        description = description.strip()
        description = re.sub(r'\s+', ' ', description)
        description = description.rstrip('.')

        status_descriptions[error_code] = description

    define_pattern = r'#define\s+(PSA_(?:SUCCESS|ERROR_\w+))\s+'

    error_codes = []
    for match in re.finditer(define_pattern, content):
        code = match.group(1)
        if code not in error_codes:
            error_codes.append(code)

    result = []
    for code in error_codes:
        description = status_descriptions.get(code, "Unknown error")
        result.append((code, description))

    success = [e for e in result if e[0] == 'PSA_SUCCESS']
    errors = [e for e in result if e[0] != 'PSA_SUCCESS']
    errors.sort(key=lambda x: x[0])

    return success + errors

def generate_complete_file(error_list):
    """Generate the complete error_handler.c file from scratch."""

    # File header
    header = """\
// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2026 NXP
 */

/* AUTO-GENERATED FILE - DO NOT EDIT */
/* Generated by scripts/generate_psa_error_table.py */

#include <stdio.h>
#include "error_handler.h"
#include "helper.h"

/* ========================================================================
 * PSA Error Handling
 * ========================================================================
 */
"""

    # Error table
    error_table = "static const struct cli_error_info psa_error_table[] = {\n"
    for error_code, description in error_list:
        error_table += f'\tERROR({error_code},\n'
        error_table += f'\t      "{description}"),\n'
    error_table += "};\n\n"

    # Helper functions
    helper_functions = """\
static const struct cli_error_info *get_psa_error_info(psa_status_t status)
{
\tsize_t i;

\tfor (i = 0; i < ARRAY_SIZE(psa_error_table); i++) {
\t\tif (psa_error_table[i].code == (int)status)
\t\t\treturn &psa_error_table[i];
\t}
\treturn NULL;
}

const char *cli_psa_status_to_name(psa_status_t status)
{
\tconst struct cli_error_info *info = get_psa_error_info(status);

\treturn info ? info->name : "UNKNOWN_STATUS";
}

const char *cli_psa_status_to_description(psa_status_t status)
{
\tconst struct cli_error_info *info = get_psa_error_info(status);

\treturn info ? info->description : "Unknown error status";
}
"""

    return header + error_table + helper_functions

def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent

    header_path = repo_root / "public" / "psa" / "error.h"

    # Default output path (can be overridden by command line argument)
    output_path = repo_root / "cli" / "psa" / "error_handler.c"

    # Check if running from CMake (binary dir path provided)
    if len(sys.argv) > 1:
        output_path = Path(sys.argv[1])

    if not header_path.exists():
        print(f"ERROR: Header file not found: {header_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing {header_path}...")
    error_list = parse_psa_error_header(header_path)

    if not error_list:
        print("ERROR: No PSA error codes found", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(error_list)} PSA error codes")

    # Generate the complete file
    file_content = generate_complete_file(error_list)

    # Write the file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(file_content)

    print(f"Generated {output_path}")

if __name__ == "__main__":
    main()
