#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 NXP

"""
Script to generate SMW hash algorithm table from public/smw/names.h
This ensures the CLI stays in sync with SMW's supported algorithms.
"""

import re
import sys
from datetime import datetime
from pathlib import Path

def parse_smw_hash_algos(header_path):
    """Parse public/smw/names.h and extract hash algorithm definitions."""

    with open(header_path, 'r') as f:
        content = f.read()

    # Find the smw_hash_algo_t typedef documentation
    typedef_pattern = r'/\*\*\s*\n\s*\* typedef smw_hash_algo_t - Hash algorithm name\s*\n\s*\*\s*\n\s*\* Values:(.*?)\*/'
    match = re.search(typedef_pattern, content, re.DOTALL)

    if not match:
        print("ERROR: Could not find smw_hash_algo_t documentation", file=sys.stderr)
        sys.exit(1)

    doc_section = match.group(1)

    # Extract algorithm descriptions from documentation
    desc_pattern = r'\*\s+\*\s+(SMW_HASH_ALGO_NAME_\w+):\s+([^\n]+)'
    descriptions = {}

    for m in re.finditer(desc_pattern, doc_section):
        algo_name = m.group(1)
        desc = m.group(2).strip()
        descriptions[algo_name] = desc

    # Find the enum body
    enum_pattern = r'typedef enum\s*\{([^}]+)\}\s*smw_hash_algo_t;'
    enum_match = re.search(enum_pattern, content)

    if not enum_match:
        print("ERROR: Could not find smw_hash_algo_t enum", file=sys.stderr)
        sys.exit(1)

    enum_body = enum_match.group(1)

    # Extract enum values
    enum_value_pattern = r'(SMW_HASH_ALGO_NAME_\w+)'
    algos = []

    for m in re.finditer(enum_value_pattern, enum_body):
        algo_name = m.group(1)
        # Skip NONE and NB
        if algo_name not in ['SMW_HASH_ALGO_NAME_NONE', 'SMW_HASH_ALGO_NAME_NB']:
            algos.append(algo_name)

    # Build algorithm info
    algo_info = []
    for algo in algos:
        cli_name = algo.replace('SMW_HASH_ALGO_NAME_', '')
        desc = descriptions.get(algo, 'Unknown algorithm')

        algo_info.append({
            'smw_name': algo,
            'cli_name': cli_name,
            'description': desc
        })

    return algo_info

def generate_file(algo_info):
    """Generate the complete SMW hash table file."""

    current_year = datetime.now().year

    header = f"""\
// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright {current_year} NXP
 */

/* AUTO-GENERATED FILE - DO NOT EDIT */
/* Generated by scripts/generate_smw_hash_table.py */

#include "hash_algo_enum.h"
#include "hash_table_generated.h"
#include "helper.h"

/**
 * SMW hash algorithm mapping
 */
struct smw_hash_algo_mapping {{
\tenum hash_algo cli_algo;
\tsmw_hash_algo_t smw_algo;
\tconst char *name;
}};

static const struct smw_hash_algo_mapping smw_hash_algos[] = {{
"""

    mappings = []
    for info in algo_info:
        mappings.append(
            f'\t{{ HASH_ALGO_{info["cli_name"]}, {info["smw_name"]}, "{info["smw_name"]}" }},'
        )

    middle = """\
};

/**
 * @brief Convert CLI hash algorithm to SMW hash algorithm
 *
 * @param algo CLI hash algorithm enum value
 */
smw_hash_algo_t cli_hash_algo_to_smw(enum hash_algo algo)
{
\tsize_t i;

\tfor (i = 0; i < ARRAY_SIZE(smw_hash_algos); i++) {
\t\tif (smw_hash_algos[i].cli_algo == algo)
\t\t\treturn smw_hash_algos[i].smw_algo;
\t}

\treturn SMW_HASH_ALGO_NAME_NONE;
}

/**
 * @brief Get SMW hash algorithm name string for logging
 *
 * @param algo SMW hash algorithm enum value
 */
const char *cli_smw_get_hash_algo_name(smw_hash_algo_t algo)
{
\tsize_t i;

\tfor (i = 0; i < ARRAY_SIZE(smw_hash_algos); i++) {
\t\tif (smw_hash_algos[i].smw_algo == algo)
\t\t\treturn smw_hash_algos[i].name;
\t}

\treturn "UNKNOWN_ALGORITHM";
}
"""

    return header + '\n'.join(mappings) + '\n' + middle

def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent

    smw_header = repo_root / "public" / "smw" / "names.h"

    # Default output path
    output_path = repo_root / "cli" / "smw" / "hash_table_generated.c"

    # Check if running from CMake (binary dir provided)
    if len(sys.argv) > 1:
        output_path = Path(sys.argv[1])

    if not smw_header.exists():
        print(f"ERROR: SMW header not found: {smw_header}", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing {smw_header}...")
    algo_info = parse_smw_hash_algos(smw_header)

    print(f"Found {len(algo_info)} SMW hash algorithms")

    # Generate file
    file_content = generate_file(algo_info)

    # Write file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(file_content)

    print(f"Generated {output_path}")

if __name__ == "__main__":
    main()
