#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 NXP

"""
Script to generate common hash algorithm tables by parsing SMW headers.
This ensures the CLI stays in sync with the actual library definitions.
"""

import re
import sys
from pathlib import Path

def generate_enum_header(algo_info):
    """Generate hash_algo_enum.h with the CLI enum."""

    header = """\
// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2026 NXP
 */

/* AUTO-GENERATED FILE - DO NOT EDIT */
/* Generated by scripts/generate_hash_common_table.py */

#ifndef CLI_HASH_ALGO_ENUM_H
#define CLI_HASH_ALGO_ENUM_H

/**
 * Hash algorithms (CLI abstraction layer)
 *
 * This enum is auto-generated from SMW's hash algorithm definitions.
 * It serves as the common interface for both SMW and PSA backends.
 */
enum hash_algo {
\tHASH_ALGO_NONE = 0,
"""

    enum_values = []
    for info in algo_info:
        enum_values.append(f"\tHASH_ALGO_{info['cli_name']},")

    footer = """\
};

#endif /* CLI_HASH_ALGO_ENUM_H */
"""

    return header + '\n'.join(enum_values) + '\n' + footer

def extract_digest_length(algo_name, description):
    """Extract digest length from algorithm name or description."""

    # Try to find bits in description
    bit_match = re.search(r'(\d+)\s*bits?', description, re.IGNORECASE)
    if bit_match:
        bits = int(bit_match.group(1))
        return bits // 8

    # Fallback: extract from algorithm name
    size_patterns = {
        '224': 28,
        '256': 32,
        '384': 48,
        '512': 64,
    }

    for pattern, size in size_patterns.items():
        if pattern in algo_name:
            return size

    # Known fixed sizes
    if 'MD5' in algo_name:
        return 16
    elif 'SHA1' in algo_name or 'SHA_1' in algo_name:
        return 20
    elif 'SM3' in algo_name:
        return 32

    # Default for unknown
    return 32

def is_xof_algorithm(algo_name, description):
    """Determine if algorithm is an XOF (Extendable-Output Function)."""
    xof_keywords = ['SHAKE', 'KECCAK', 'extendable', 'XOF']

    for keyword in xof_keywords:
        if keyword.upper() in algo_name.upper() or keyword.upper() in description.upper():
            return True

    return False

def enhance_description(cli_name, description, is_xof):
    """Enhance description for CLI display."""
    if is_xof:
        return f"{description.rstrip('.')} (XOF, use -l to set length)"
    return description

def parse_smw_hash_algos(header_path):
    """Parse public/smw/names.h and extract hash algorithm definitions."""

    with open(header_path, 'r') as f:
        content = f.read()

    # Find the smw_hash_algo_t typedef documentation
    typedef_pattern = r'/\*\*\s*\n\s*\* typedef smw_hash_algo_t - Hash algorithm name\s*\n\s*\*\s*\n\s*\* Values:(.*?)\*/'
    match = re.search(typedef_pattern, content, re.DOTALL)

    if not match:
        print("ERROR: Could not find smw_hash_algo_t documentation", file=sys.stderr)
        sys.exit(1)

    doc_section = match.group(1)

    # Extract algorithm descriptions from documentation
    desc_pattern = r'\*\s+\*\s+(SMW_HASH_ALGO_NAME_\w+):\s+([^\n]+)'
    descriptions = {}

    for m in re.finditer(desc_pattern, doc_section):
        algo_name = m.group(1)
        desc = m.group(2).strip()
        descriptions[algo_name] = desc

    # Find the enum body
    enum_pattern = r'typedef enum\s*\{([^}]+)\}\s*smw_hash_algo_t;'
    enum_match = re.search(enum_pattern, content)

    if not enum_match:
        print("ERROR: Could not find smw_hash_algo_t enum", file=sys.stderr)
        sys.exit(1)

    enum_body = enum_match.group(1)

    # Extract enum values
    enum_value_pattern = r'(SMW_HASH_ALGO_NAME_\w+)'
    algos = []

    for m in re.finditer(enum_value_pattern, enum_body):
        algo_name = m.group(1)
        # Skip NONE and NB
        if algo_name not in ['SMW_HASH_ALGO_NAME_NONE', 'SMW_HASH_ALGO_NAME_NB']:
            algos.append(algo_name)

    # Build algorithm info with dynamic metadata
    algo_info = []
    for algo in algos:
        cli_name = algo.replace('SMW_HASH_ALGO_NAME_', '')
        raw_desc = descriptions.get(algo, 'Unknown algorithm')

        # Dynamically determine properties
        digest_len = extract_digest_length(cli_name, raw_desc)
        is_xof = is_xof_algorithm(cli_name, raw_desc)
        description = enhance_description(cli_name, raw_desc, is_xof)

        algo_info.append({
            'cli_name': cli_name,
            'digest_len': digest_len,
            'is_xof': is_xof,
            'description': description
        })

    return algo_info

def generate_header_file():
    """Generate hash_table_generated.h"""

    return """\
// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2026 NXP
 */

/* AUTO-GENERATED FILE - DO NOT EDIT */
/* Generated by scripts/generate_hash_common_table.py */

#ifndef CLI_HASH_TABLE_GENERATED_H
#define CLI_HASH_TABLE_GENERATED_H

#include <psa/crypto.h>
#include <stdbool.h>
#include <stddef.h>
#include <smw_crypto.h>
#include "hash_algo_enum.h"

/**
 * Hash algorithm information table
 */
struct hash_algo_info {
\tenum hash_algo algo;
\tconst char *name;
\tunsigned int digest_len;
\tbool is_xof;
\tconst char *description;
};

extern const struct hash_algo_info hash_algo_table[];
extern const size_t hash_algo_table_size;

size_t get_hash_output_length(enum hash_algo algo);

bool is_hash_algo_xof(enum hash_algo algo);

/* PSA-specific functions (defined in psa/hash_table_generated.c) */
psa_algorithm_t cli_hash_algo_to_psa(enum hash_algo algo);
const char *psa_hash_algo_to_string(psa_algorithm_t alg);

/* SMW-specific functions (defined in smw/hash_table_generated.c) */
smw_hash_algo_t cli_hash_algo_to_smw(enum hash_algo algo);
const char *cli_smw_get_hash_algo_name(smw_hash_algo_t algo);

#endif /* CLI_HASH_TABLE_GENERATED_H */
"""

def generate_source_file(algo_info):
    """Generate hash_table_generated.c from parsed algorithm info."""

    header = """\
// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2026 NXP
 */

/* AUTO-GENERATED FILE - DO NOT EDIT */
/* Generated by scripts/generate_hash_common_table.py */

#include "hash_table_generated.h"

const struct hash_algo_info hash_algo_table[] = {
"""

    table_entries = []
    for info in algo_info:
        xof_str = 'true' if info['is_xof'] else 'false'
        table_entries.append(
            f'\t{{ HASH_ALGO_{info["cli_name"]}, "{info["cli_name"]}", '
            f'{info["digest_len"]}, {xof_str}, "{info["description"]}" }},'
        )

        footer = """\
};

const size_t hash_algo_table_size = sizeof(hash_algo_table) / sizeof(hash_algo_table[0]);

/**
 * @brief Get hash output length for a given algorithm
 *
 * @param algo Hash algorithm enum value
 */
size_t get_hash_output_length(enum hash_algo algo)
{
\tsize_t i;

\tfor (i = 0; i < hash_algo_table_size; i++) {
\t\tif (hash_algo_table[i].algo == algo)
\t\t\treturn hash_algo_table[i].digest_len;
\t}

\treturn 0;
}

/**
 * @brief Check if hash algorithm is an XOF (Extendable-Output Function)
 *
 * @param algo Hash algorithm enum value
 */
bool is_hash_algo_xof(enum hash_algo algo)
{
\tsize_t i;

\tfor (i = 0; i < hash_algo_table_size; i++) {
\t\tif (hash_algo_table[i].algo == algo)
\t\t\treturn hash_algo_table[i].is_xof;
\t}

\treturn false;
}
"""

    return header + '\n'.join(table_entries) + '\n' + footer

def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent

    smw_header = repo_root / "public" / "smw" / "names.h"

    # Paths provided by CMake (build directory)
    if len(sys.argv) != 4:
        print("Usage: generate_hash_common_table.py <enum.h> <table.h> <table.c>", file=sys.stderr)
        sys.exit(1)

    output_enum = Path(sys.argv[1])
    output_h = Path(sys.argv[2])
    output_c = Path(sys.argv[3])

    if not smw_header.exists():
        print(f"ERROR: SMW header not found: {smw_header}", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing {smw_header}...")
    algo_info = parse_smw_hash_algos(smw_header)

    print(f"Found {len(algo_info)} hash algorithms")

    # Generate enum header
    enum_content = generate_enum_header(algo_info)
    output_enum.parent.mkdir(parents=True, exist_ok=True)
    with open(output_enum, 'w') as f:
        f.write(enum_content)
    print(f"Generated {output_enum}")

    # Generate table header
    header_content = generate_header_file()
    output_h.parent.mkdir(parents=True, exist_ok=True)
    with open(output_h, 'w') as f:
        f.write(header_content)
    print(f"Generated {output_h}")

    # Generate table source
    source_content = generate_source_file(algo_info)
    output_c.parent.mkdir(parents=True, exist_ok=True)
    with open(output_c, 'w') as f:
        f.write(source_content)
    print(f"Generated {output_c}")

if __name__ == "__main__":
    main()
