#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 NXP

"""
Script to generate PSA hash algorithm table from public/psa/crypto_values.h
This ensures the CLI stays in sync with PSA's supported algorithms.
"""

import re
import sys
from pathlib import Path

def parse_psa_hash_algos(header_path):
    """Parse public/psa/crypto_values.h and extract PSA hash algorithm definitions."""

    with open(header_path, 'r') as f:
        content = f.read()

    # Find hash algorithm #defines
    # Look for lines like: #define PSA_ALG_SHA_256 ((psa_algorithm_t)0x02000009)
    pattern = r'#define\s+(PSA_ALG_(?:MD5|SHA_\d+|SHA3_\d+|SM3|SHAKE256_512))\s+\(\(psa_algorithm_t\)0x[0-9a-fA-F]+\)'

    psa_algos = []
    for match in re.finditer(pattern, content):
        psa_name = match.group(1)

        # Convert PSA name to CLI name
        cli_name = psa_name.replace('PSA_ALG_', '')

        # Special case: SHA_1 -> SHA1
        if cli_name == 'SHA_1':
            cli_name = 'SHA1'
        # SHA_256 -> SHA256, etc.
        elif cli_name.startswith('SHA_'):
            cli_name = cli_name.replace('SHA_', 'SHA')
        elif cli_name.startswith('SHA3_'):
            cli_name = cli_name.replace('SHA3_', 'SHA3_')
        # SHAKE256_512 -> SHAKE256
        elif cli_name == 'SHAKE256_512':
            cli_name = 'SHAKE256'

        psa_algos.append({
            'psa_name': psa_name,
            'cli_name': cli_name
        })

    return psa_algos

def generate_file(psa_algos):
    """Generate the complete PSA hash table file."""

    header = """\
// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2026 NXP
 */

/* AUTO-GENERATED FILE - DO NOT EDIT */
/* Generated by scripts/generate_psa_hash_table.py */

#include "hash_algo_enum.h"
#include "hash_table_generated.h"
#include "helper.h"

/**
 * PSA hash algorithm mapping
 */
struct psa_hash_algo_mapping {
\tenum hash_algo cli_algo;
\tpsa_algorithm_t psa_algo;
\tconst char *name;
};

static const struct psa_hash_algo_mapping psa_hash_algos[] = {
"""

    mappings = []
    for info in psa_algos:
        mappings.append(
            f'\t{{ HASH_ALGO_{info["cli_name"]}, {info["psa_name"]}, "{info["psa_name"]}" }},'
        )

    middle = """\
};

/**
 * @brief Convert CLI hash algorithm to PSA hash algorithm
 *
 * @param algo CLI hash algorithm enum value
 */
psa_algorithm_t cli_hash_algo_to_psa(enum hash_algo algo)
{
\tsize_t i;

\tfor (i = 0; i < ARRAY_SIZE(psa_hash_algos); i++) {
\t\tif (psa_hash_algos[i].cli_algo == algo)
\t\t\treturn psa_hash_algos[i].psa_algo;
\t}

\treturn 0;
}

/**
 * @brief Get PSA algorithm name string
 *
 * @param alg PSA algorithm value
 */
const char *psa_hash_algo_to_string(psa_algorithm_t alg)
{
\tsize_t i;

\tfor (i = 0; i < ARRAY_SIZE(psa_hash_algos); i++) {
\t\tif (psa_hash_algos[i].psa_algo == alg)
\t\t\treturn psa_hash_algos[i].name;
\t}

\treturn "UNKNOWN_ALGORITHM";
}
"""

    return header + '\n'.join(mappings) + '\n' + middle

def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent

    psa_header = repo_root / "public" / "psa" / "crypto_values.h"

    # Default output path
    output_path = repo_root / "cli" / "psa" / "hash_table_generated.c"

    # Check if running from CMake (binary dir provided)
    if len(sys.argv) > 1:
        output_path = Path(sys.argv[1])

    if not psa_header.exists():
        print(f"ERROR: PSA header not found: {psa_header}", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing {psa_header}...")
    psa_algos = parse_psa_hash_algos(psa_header)

    print(f"Found {len(psa_algos)} PSA hash algorithms")

    # Generate file
    file_content = generate_file(psa_algos)

    # Write file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(file_content)

    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
