#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 NXP

"""
Script to generate SMW error handler from public/smw_status.h
This ensures the error descriptions stay in sync with the status codes.
"""

import re
import sys
from datetime import datetime
from pathlib import Path


def parse_status_header(header_path):
    """Parse smw_status.h and extract status codes with descriptions."""

    with open(header_path, 'r') as f:
        content = f.read()

    enum_doc_pattern = r'/\*\*\s*\n\s*\* enum smw_status_code.*?\*/'
    enum_doc_match = re.search(enum_doc_pattern, content, re.DOTALL)

    if not enum_doc_match:
        print("ERROR: Could not find enum smw_status_code documentation", file=sys.stderr)
        sys.exit(1)

    enum_doc = enum_doc_match.group(0)

    classification_start = enum_doc.find('Status code classification')
    if classification_start != -1:
        enum_doc = enum_doc[:classification_start]

    status_pattern = r'@(SMW_STATUS_\w+):\s*([^@]+?)(?=\s*(?:@|$))'

    status_descriptions = {}
    for match in re.finditer(status_pattern, enum_doc, re.DOTALL):
        status_code = match.group(1)
        description = match.group(2)

        description = re.sub(r'\s*\n\s*\*\s*', ' ', description)
        description = description.strip()
        description = re.sub(r'\s+', ' ', description)

        sentence_end = re.search(r'\.\s+(?=[A-Z])', description)
        if sentence_end:
            description = description[:sentence_end.start() + 1]

        # description = shorten_description(description)
        description = description.rstrip('.').rstrip('*').rstrip('/').strip()

        status_descriptions[status_code] = description

    enum_pattern = r'enum smw_status_code\s*\{([^}]+)\}'
    enum_match = re.search(enum_pattern, content, re.DOTALL)

    if not enum_match:
        print("ERROR: Could not find enum smw_status_code definition", file=sys.stderr)
        sys.exit(1)

    enum_body = enum_match.group(1)

    code_pattern = r'(SMW_STATUS_\w+)'
    status_codes = []

    for match in re.finditer(code_pattern, enum_body):
        code = match.group(1)
        if code not in status_codes:
            status_codes.append(code)

    return [(code, status_descriptions.get(code, "Unknown error")) for code in status_codes]

def generate_complete_file(status_list):
    """Generate the complete error_handler.c file from scratch."""

    current_year = datetime.now().year

    # File header
    header = f"""\
// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright {current_year} NXP
 */

/* AUTO-GENERATED FILE - DO NOT EDIT */
/* Generated by scripts/generate_smw_error_table.py */

#include <stdio.h>
#include "error_handler.h"
#include "helper.h"

/* ========================================================================
 * SMW Error Handling
 * ========================================================================
 */
"""

    # Error table
    error_table = "static const struct cli_error_info smw_error_table[] = {\n"
    for status_code, description in status_list:
        error_table += f'\tERROR({status_code},\n'
        error_table += f'\t      "{description}"),\n'
    error_table += "};\n\n"

    # Helper functions
    helper_functions = """\
static const struct cli_error_info *get_smw_error_info(enum smw_status_code status)
{
\tsize_t i;

\tfor (i = 0; i < ARRAY_SIZE(smw_error_table); i++) {
\t\tif (smw_error_table[i].code == (int)status)
\t\t\treturn &smw_error_table[i];
\t}
\treturn NULL;
}

const char *cli_smw_status_to_name(enum smw_status_code status)
{
\tconst struct cli_error_info *info = get_smw_error_info(status);

\treturn info ? info->name : "UNKNOWN_STATUS";
}

const char *cli_smw_status_to_description(enum smw_status_code status)
{
\tconst struct cli_error_info *info = get_smw_error_info(status);

\treturn info ? info->description : "Unknown error status";
}
"""

    return header + error_table + helper_functions

def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent

    header_path = repo_root / "public" / "smw_status.h"

    # Default output path (can be overridden by command line argument)
    output_path = repo_root / "cli" / "smw" / "error_handler.c"

    # Check if running from CMake (binary dir path provided)
    if len(sys.argv) > 1:
        output_path = Path(sys.argv[1])

    if not header_path.exists():
        print(f"ERROR: Header file not found: {header_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing {header_path}...")
    status_list = parse_status_header(header_path)

    print(f"Found {len(status_list)} status codes")

    # Generate the complete file
    file_content = generate_complete_file(status_list)

    # Write the file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(file_content)

    print(f"Generated {output_path}")

if __name__ == "__main__":
    main()
