#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 NXP

"""
Script to generate lifecycle mapping table from public/smw/names.h
This ensures the lifecycle names and descriptions stay in sync with the enum definitions.
"""

import re
import sys
from pathlib import Path
from datetime import datetime


def parse_smw_lifecycles(header_path):
    """Parse public/smw/names.h and extract lifecycle definitions with descriptions."""

    with open(header_path, 'r') as f:
        content = f.read()

    # Find the smw_lifecycle_t typedef documentation
    typedef_pattern = r'/\*\*\s*\n\s*\* typedef smw_lifecycle_t - Device lifecycle name\s*\n\s*\*\s*\n\s*\* Values:(.*?)\*/'
    match = re.search(typedef_pattern, content, re.DOTALL)

    if not match:
        print("ERROR: Could not find smw_lifecycle_t documentation", file=sys.stderr)
        sys.exit(1)

    doc_section = match.group(1)

    # Extract lifecycle descriptions from documentation
    desc_pattern = r'\*\s+\*\s+(SMW_LIFECYCLE_NAME_\w+):\s+([^\n]+)'
    descriptions = {}

    for m in re.finditer(desc_pattern, doc_section):
        lifecycle_name = m.group(1)
        desc = m.group(2).strip()
        descriptions[lifecycle_name] = desc

    # Find the enum body
    enum_pattern = r'typedef enum\s*\{([^}]+)\}\s*smw_lifecycle_t;'
    enum_match = re.search(enum_pattern, content)

    if not enum_match:
        print("ERROR: Could not find smw_lifecycle_t enum definition", file=sys.stderr)
        sys.exit(1)

    enum_body = enum_match.group(1)

    # Extract enum values
    enum_value_pattern = r'(SMW_LIFECYCLE_NAME_\w+)'
    lifecycles = []

    for m in re.finditer(enum_value_pattern, enum_body):
        lifecycle_name = m.group(1)
        if lifecycle_name not in lifecycles:
            lifecycles.append(lifecycle_name)

    # Build lifecycle info
    lifecycle_info = []
    for lc in lifecycles:
        # Skip NONE and NB
        if lc in ['SMW_LIFECYCLE_NAME_NONE', 'SMW_LIFECYCLE_NAME_NB']:
            continue

        cli_name = lc.replace('SMW_LIFECYCLE_NAME_', '')
        description = descriptions.get(lc, 'Unknown lifecycle')

        lifecycle_info.append({
            'smw_name': lc,
            'cli_name': cli_name,
            'description': description
        })

    return lifecycle_info


def generate_header_file():
    """Generate lifecycle_table.h"""

    current_year = datetime.now().year

    return f"""\
// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright {current_year} NXP
 */

/* AUTO-GENERATED FILE - DO NOT EDIT */
/* Generated by scripts/generate_lifecycle_table.py */

#ifndef CLI_LIFECYCLE_TABLE_H
#define CLI_LIFECYCLE_TABLE_H

#include <smw/names.h>
#include <stddef.h>

/**
 * struct lifecycle_info - Lifecycle information
 * @smw_value: SMW lifecycle enum value
 * @name: String representation of lifecycle
 * @description: Human-readable description
 */
struct lifecycle_info {{
\tsmw_lifecycle_t smw_value;
\tconst char *name;
\tconst char *description;
}};

extern const struct lifecycle_info lifecycle_table[];
extern const size_t lifecycle_table_size;

/**
 * lifecycle_name_to_string() - Convert lifecycle enum to string
 * @lifecycle: Lifecycle enum value
 *
 * Return: Lifecycle name string or "UNKNOWN"
 */
const char *lifecycle_name_to_string(smw_lifecycle_t lifecycle);

/**
 * string_to_lifecycle_name() - Convert string to lifecycle enum
 * @name: Lifecycle name string
 *
 * Return: Lifecycle enum value or SMW_LIFECYCLE_NAME_NONE if not found
 */
smw_lifecycle_t string_to_lifecycle_name(const char *name);

void print_lifecycle_list(void);

#endif /* CLI_LIFECYCLE_TABLE_H */
"""


def generate_source_file(lifecycle_info):
    """Generate lifecycle_table.c from parsed lifecycle info."""

    current_year = datetime.now().year

    header = f"""\
// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright {current_year} NXP
 */

/* AUTO-GENERATED FILE - DO NOT EDIT */
/* Generated by scripts/generate_lifecycle_table.py */

#include <stdio.h>
#include <string.h>
#include "lifecycle_table.h"

const struct lifecycle_info lifecycle_table[] = {{
"""

    table_entries = []
    for info in lifecycle_info:
        table_entries.append(
            f'\t{{ {info["smw_name"]}, "{info["cli_name"]}", "{info["description"]}" }},'
        )

    footer = """\
};

const size_t lifecycle_table_size = sizeof(lifecycle_table) / sizeof(lifecycle_table[0]);

/**
 * lifecycle_name_to_string() - Convert lifecycle enum to string
 * @lifecycle: Lifecycle enum value
 *
 * Return: Lifecycle name string or "UNKNOWN"
 */
const char *lifecycle_name_to_string(smw_lifecycle_t lifecycle)
{
\tsize_t i = 0;

\tfor (i = 0; i < lifecycle_table_size; i++) {
\t\tif (lifecycle_table[i].smw_value == lifecycle)
\t\t\treturn lifecycle_table[i].name;
\t}

\treturn "UNKNOWN";
}

/**
 * string_to_lifecycle_name() - Convert string to lifecycle enum
 * @name: Lifecycle name string
 *
 * Return: Lifecycle enum value or SMW_LIFECYCLE_NAME_NONE if not found
 */
smw_lifecycle_t string_to_lifecycle_name(const char *name)
{
\tsize_t i = 0;

\tif (!name)
\t\treturn SMW_LIFECYCLE_NAME_NONE;

\tfor (i = 0; i < lifecycle_table_size; i++) {
\t\tif (strcmp(lifecycle_table[i].name, name) == 0)
\t\t\treturn lifecycle_table[i].smw_value;
\t}

\treturn SMW_LIFECYCLE_NAME_NONE;
}

/**
 * @brief Print list of available lifecycle values
 */
void print_lifecycle_list(void)
{
\tsize_t i = 0;
\tconst struct lifecycle_info *info = NULL;

\tprintf("\\n");
\tprintf("Available Device Lifecycle Values\\n");
\tprintf("=================================\\n\\n");
\tprintf("%-20s %s\\n", "Lifecycle", "Description");
\tprintf("%-20s %s\\n", "---------", "-----------");

\tfor (; i < lifecycle_table_size; i++) {
\t\tinfo = &lifecycle_table[i];

\t\tif (strstr(info->description, "Deprecated"))
\t\t\tcontinue;

\t\tprintf("%-20s %s\\n", info->name, info->description);
\t}

\tprintf("\\nNote: Actual support depends on the backend and subsystem capabilities.\\n");
\tprintf("      The operation may fail at runtime if unsupported.\\n\\n");
}
"""

    return header + '\n'.join(table_entries) + '\n' + footer


def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent

    smw_header = repo_root / "public" / "smw" / "names.h"

    # Paths provided by CMake (build directory)
    if len(sys.argv) != 3:
        print("Usage: generate_lifecycle_table.py <table.h> <table.c>", file=sys.stderr)
        sys.exit(1)

    output_h = Path(sys.argv[1])
    output_c = Path(sys.argv[2])

    if not smw_header.exists():
        print(f"ERROR: SMW header not found: {smw_header}", file=sys.stderr)
        sys.exit(1)

    print(f"Parsing {smw_header}...")
    lifecycle_info = parse_smw_lifecycles(smw_header)

    print(f"Found {len(lifecycle_info)} lifecycle values")

    # Generate table header
    header_content = generate_header_file()
    output_h.parent.mkdir(parents=True, exist_ok=True)
    with open(output_h, 'w') as f:
        f.write(header_content)
    print(f"Generated {output_h}")

    # Generate table source
    source_content = generate_source_file(lifecycle_info)
    output_c.parent.mkdir(parents=True, exist_ok=True)
    with open(output_c, 'w') as f:
        f.write(source_content)
    print(f"Generated {output_c}")


if __name__ == "__main__":
    main()
