// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2020, 2024-2026 NXP
 */

#include "lib_object.h"

/**
 * C_GenerateKey() - Generates a symmetric key.
 * @hSession: [in] The session's handle.
 * @pMechanism: [in] Pointer to the key generation mechanism.
 * @pTemplate: [in] Pointer to the template of the key attributes to create.
 * @ulCount: [in] Number of attributes in the template.
 * @phKey: [out] Pointer to the location that receives the handle of the new key.
 *
 * This function generates a symmetric key, creating a new key object.
 *
 * The type of key generated depends on the mechanism specified, hence
 * it is not necessary to specify key type in template. If specified, it must
 * match the key type generated by the mechanism otherwise function returns
 * CKR_TEMPLATE_INCONSISTENT error.
 *
 * The class CKA_CLASS attribute is not needed as well, if specified and not
 * CKO_SECRET_KEY, the function returns CKR_TEMPLATE_INCONSISTENT error.
 *
 * Return:
 *  - CKR_OK:
 *      Success.
 *  - CKR_ARGUMENTS_BAD:
 *      The @phKey is NULL.
 *  - CKR_SESSION_HANDLE_INVALID:
 *      The session handle is not valid.
 *  - CKR_MECHANISM_PARAM_INVALID:
 *      The @pMechanism is NULL.
 *  - CKR_TEMPLATE_INCOMPLETE:
 *      The @pTemplate and @ulCount is incomplete or inconsistent.
 *  - CKR_TEMPLATE_INCONSISTENT:
 *      One of the template's attribute type must not be defined.
 *  - CKR_ATTRIBUTE_READ_ONLY:
 *      One attribute is read only
 *  - CKR_ATTRIBUTE_VALUE_INVALID:
 *      One of the template's attribute value is not valid.
 *  - CKR_USER_NOT_LOGGED_IN:
 *      User must login to create object.
 *  - CKR_SLOT_ID_INVALID:
 *      Slot ID is not valid.
 *  - CKR_MECHANISM_INVALID:
 *      Mechanism not supported.
 *  - CKR_HOST_MEMORY:
 *      Allocation error.
 *  - CKR_SESSION_CLOSED:
 *      Session closed.
 *  - CKR_FUNCTION_FAILED:
 *      Function failure.
 *  - CKR_FUNCTION_CANCELED:
 *      Application callback canceled function.
 *  - CKR_TOKEN_NOT_PRESENT:
 *      Token not present.
 *  - CKR_GENERAL_ERROR:
 *      General error.
 *  - CKR_CRYPTOKI_NOT_INITIALIZED:
 *      The library has not been previously initialized by :c:func:`C_Initialize`.
 *  - Other errors from the underlying implementation.
 */
CK_RV C_GenerateKey(CK_SESSION_HANDLE hSession, CK_MECHANISM_PTR pMechanism,
		    CK_ATTRIBUTE_PTR pTemplate, CK_ULONG ulCount,
		    CK_OBJECT_HANDLE_PTR phKey)
{
	if (!hSession)
		return CKR_SESSION_HANDLE_INVALID;

	if (!pMechanism)
		return CKR_MECHANISM_PARAM_INVALID;

	/*
	 * Key template attributes may not be necessary
	 */
	if ((!pTemplate && ulCount) || (pTemplate && !ulCount))
		return CKR_TEMPLATE_INCOMPLETE;

	if (!phKey)
		return CKR_ARGUMENTS_BAD;

	return libobj_generate_key(hSession, pMechanism, pTemplate, ulCount,
				   phKey);
}

/**
 * C_GenerateKeyPair() - Generates an asymmetric key pair.
 * @hSession: [in] The session's handle.
 * @pMechanism: [in] Pointer to the key generation mechanism.
 * @pPublicKeyTemplate: [in] Pointer to the template of the public key
 *                           attributes to create.
 * @ulPublicKeyAttributeCount: [in] Number of attributes in the public key
 *                                  template.
 * @pPrivateKeyTemplate: [in] Pointer to the template of the private key
 *                            attributes to create.
 * @ulPrivateKeyAttributeCount: [in] Number of attributes in the private key
 *                                   template.
 * @phPublicKey: [out] Pointer to the location that receives the handle of the
 *                     public key.
 * @phPrivateKey: [out] Pointer to the location that receives the handle of the
 *                      private key.
 *
 * This function generates an asymmetric key pair, creating new key objects.
 *
 * The type of key generated depends on the mechanism specified, hence
 * it is not necessary to specify key type in templates. If specified, it must
 * match the key type generated by the mechanism otherwise function returns
 * CKR_TEMPLATE_INCONSISTENT error.
 *
 * The class CKA_CLASS attribute is not needed as well, if specified and not
 * CKO_PUBLIC_KEY or CKO_PRIVATE_KEY in the respective Public and Private
 * template, the function returns CKR_TEMPLATE_INCONSISTENT error.
 *
 * Return:
 *  - CKR_OK:
 *      Success.
 *  - CKR_ARGUMENTS_BAD:
 *      - The @phPublic is NULL.
 *      - The @phPrivateKey is NULL.
 *  - CKR_SESSION_HANDLE_INVALID:
 *      The session handle is not valid.
 *  - CKR_MECHANISM_PARAM_INVALID:
 *      The @pMechanism is NULL.
 *  - CKR_TEMPLATE_INCOMPLETE:
 *      The @pTemplate and @ulCount is incomplete or inconsistent.
 *  - CKR_TEMPLATE_INCONSISTENT:
 *      One of the template's attribute type must not be defined.
 *  - CKR_ATTRIBUTE_READ_ONLY:
 *      One attribute is read only
 *  - CKR_ATTRIBUTE_VALUE_INVALID:
 *      One of the template's attribute value is not valid.
 *  - CKR_USER_NOT_LOGGED_IN:
 *      User must login to create object.
 *  - CKR_SLOT_ID_INVALID:
 *      Slot ID is not valid.
 *  - CKR_MECHANISM_INVALID:
 *      Mechanism not supported.
 *  - CKR_HOST_MEMORY:
 *      Allocation error.
 *  - CKR_SESSION_CLOSED:
 *      Session closed.
 *  - CKR_FUNCTION_FAILED:
 *      Function failure.
 *  - CKR_FUNCTION_CANCELED:
 *      Application callback canceled function.
 *  - CKR_TOKEN_NOT_PRESENT:
 *      Token not present.
 *  - CKR_GENERAL_ERROR:
 *      General error.
 *  - CKR_CRYPTOKI_NOT_INITIALIZED:
 *      The library has not been previously initialized by :c:func:`C_Initialize`.
 *  - Other errors from the underlying implementation.
 */
CK_RV C_GenerateKeyPair(CK_SESSION_HANDLE hSession, CK_MECHANISM_PTR pMechanism,
			CK_ATTRIBUTE_PTR pPublicKeyTemplate,
			CK_ULONG ulPublicKeyAttributeCount,
			CK_ATTRIBUTE_PTR pPrivateKeyTemplate,
			CK_ULONG ulPrivateKeyAttributeCount,
			CK_OBJECT_HANDLE_PTR phPublicKey,
			CK_OBJECT_HANDLE_PTR phPrivateKey)
{
	if (!hSession)
		return CKR_SESSION_HANDLE_INVALID;

	if (!pMechanism)
		return CKR_MECHANISM_PARAM_INVALID;

	if (!pPublicKeyTemplate || !ulPublicKeyAttributeCount)
		return CKR_TEMPLATE_INCOMPLETE;

	/*
	 * Private key template attributes may not be necessary
	 */
	if ((!pPrivateKeyTemplate && ulPrivateKeyAttributeCount) ||
	    (pPrivateKeyTemplate && !ulPrivateKeyAttributeCount))
		return CKR_TEMPLATE_INCOMPLETE;

	if (!phPublicKey || !phPrivateKey)
		return CKR_ARGUMENTS_BAD;

	return libobj_generate_keypair(hSession, pMechanism, pPublicKeyTemplate,
				       ulPublicKeyAttributeCount,
				       pPrivateKeyTemplate,
				       ulPrivateKeyAttributeCount, phPublicKey,
				       phPrivateKey);
}

/**
 * C_WrapKey() - Wraps (encrypts) a private or secret key.
 * @hSession: [in] The session's handle.
 * @pMechanism: [in] Pointer to the wrapping mechanism.
 * @hWrappingKey: [in] Handle of the wrapping key.
 * @hKey: [in] Handle of the key to be wrapped.
 * @pWrappedKey: [out] Pointer to the location that receives the wrapped key,
 *                     or :c:macro:`NULL_PTR` to query the wrapped key size.
 * @pulWrappedKeyLen: [in/out] Pointer to the location that gives the size of
 *                             @pWrappedKey buffer, or receives the wrapped key
 *                             length.
 *
 * This function wraps (encrypts) a private or secret key.
 *
 * .. warning::
 *    This function is not supported.
 *
 * Return:
 *  - CKR_FUNCTION_NOT_SUPPORTED:
 *      Function is not supported.
 */
CK_RV C_WrapKey(CK_SESSION_HANDLE hSession, CK_MECHANISM_PTR pMechanism,
		CK_OBJECT_HANDLE hWrappingKey, CK_OBJECT_HANDLE hKey,
		CK_BYTE_PTR pWrappedKey, CK_ULONG_PTR pulWrappedKeyLen)
{
	(void)hSession;
	(void)pMechanism;
	(void)hWrappingKey;
	(void)hKey;
	(void)pWrappedKey;
	(void)pulWrappedKeyLen;

	return CKR_FUNCTION_NOT_SUPPORTED;
}

/**
 * C_UnwrapKey() - Unwraps (decrypts) a private or secret key.
 * @hSession: [in] The session's handle.
 * @pMechanism: [in] Pointer to the unwrapping mechanism.
 * @hUnwrappingKey: [in] Handle of the unwrapping key.
 * @pWrappedKey: [in] Pointer to the wrapped key.
 * @ulWrappedKeyLen: [in] Length of the wrapped key.
 * @pTemplate: [in] Pointer to the template attributes for the unwrapped key.
 * @ulAttributeCount: [in] Number of attributes in the template.
 * @phKey: [out] Pointer to the location that receives the handle of the
 *              unwrapped key.
 *
 * This function unwraps (decrypts) a private or secret key and creates a new
 * key.
 *
 * .. warning::
 *    This function is not supported.
 *
 * Return:
 *  - CKR_FUNCTION_NOT_SUPPORTED:
 *      Function is not supported.
 */
CK_RV C_UnwrapKey(CK_SESSION_HANDLE hSession, CK_MECHANISM_PTR pMechanism,
		  CK_OBJECT_HANDLE hUnwrappingKey, CK_BYTE_PTR pWrappedKey,
		  CK_ULONG ulWrappedKeyLen, CK_ATTRIBUTE_PTR pTemplate,
		  CK_ULONG ulAttributeCount, CK_OBJECT_HANDLE_PTR phKey)
{
	(void)hSession;
	(void)pMechanism;
	(void)hUnwrappingKey;
	(void)pWrappedKey;
	(void)ulWrappedKeyLen;
	(void)pTemplate;
	(void)ulAttributeCount;
	(void)phKey;

	return CKR_FUNCTION_NOT_SUPPORTED;
}

/**
 * C_WrapKeyAuthenticated() - Wraps a private or secret key with authenticated
 *                            encryption.
 * @hSession: [in] The session's handle.
 * @pMechanism: [in] Pointer to the wrapping mechanism.
 * @hWrappingKey: [in] Handle of the wrapping key.
 * @hKey: [in] Handle of the key to be wrapped.
 * @pAssociatedData: [in] Pointer to associated data for authenticated
 *                        encryption.
 * @ulAssociatedDataLen: [in] Length of the associated data.
 * @pWrappedKey: [out] Pointer to the location that receives the wrapped key,
 *                     or :c:macro:`NULL_PTR` to query the wrapped key size.
 * @pulWrappedKeyLen: [in/out] Pointer to the location that gives the size of
 *                             @pWrappedKey buffer, or receives the wrapped key
 *                             length.
 *
 * This function wraps a private or secret key using authenticated encryption.
 *
 * .. warning::
 *    This function is not supported.
 *
 * Return:
 *  - CKR_FUNCTION_NOT_SUPPORTED:
 *      Function is not supported.
 */
CK_RV C_WrapKeyAuthenticated(CK_SESSION_HANDLE hSession,
			     CK_MECHANISM_PTR pMechanism,
			     CK_OBJECT_HANDLE hWrappingKey,
			     CK_OBJECT_HANDLE hKey, CK_BYTE_PTR pAssociatedData,
			     CK_ULONG ulAssociatedDataLen,
			     CK_BYTE_PTR pWrappedKey,
			     CK_ULONG_PTR pulWrappedKeyLen)
{
	(void)hSession;
	(void)pMechanism;
	(void)hWrappingKey;
	(void)hKey;
	(void)pAssociatedData;
	(void)ulAssociatedDataLen;
	(void)pWrappedKey;
	(void)pulWrappedKeyLen;

	return CKR_FUNCTION_NOT_SUPPORTED;
}

/**
 * C_UnwrapKeyAuthenticated() - Unwraps a private or secret key with
 *                              authenticated decryption.
 * @hSession: [in] The session's handle.
 * @pMechanism: [in] Pointer to the unwrapping mechanism.
 * @hUnwrappingKey: [in] Handle of the unwrapping key.
 * @pWrappedKey: [in] Pointer to the wrapped key.
 * @ulWrappedKeyLen: [in] Length of the wrapped key.
 * @pTemplate: [in] Pointer to the template attributes for the unwrapped key.
 * @ulAttributeCount: [in] Number of attributes in the template.
 * @pAssociatedData: [in] Pointer to associated data for authenticated
 *                        decryption.
 * @ulAssociatedDataLen: [in] Length of the associated data.
 * @phKey: [out] Pointer to the location that receives the handle of the
 *               unwrapped key.
 *
 * This function unwraps a private or secreat key using authenticated
 * decryption and creates a new key.
 *
 * .. warning::
 *    This function is not supported.
 *
 * Return:
 *  - CKR_FUNCTION_NOT_SUPPORTED:
 *      Function is not supported.
 */
CK_RV
/* Without this comment clang-format does not meet the checkpatch requirement. */
C_UnwrapKeyAuthenticated(CK_SESSION_HANDLE hSession,
			 CK_MECHANISM_PTR pMechanism,
			 CK_OBJECT_HANDLE hUnwrappingKey,
			 CK_BYTE_PTR pWrappedKey, CK_ULONG ulWrappedKeyLen,
			 CK_ATTRIBUTE_PTR pTemplate, CK_ULONG ulAttributeCount,
			 CK_BYTE_PTR pAssociatedData,
			 CK_ULONG ulAssociatedDataLen,
			 CK_OBJECT_HANDLE_PTR phKey)
{
	(void)hSession;
	(void)pMechanism;
	(void)hUnwrappingKey;
	(void)pWrappedKey;
	(void)ulWrappedKeyLen;
	(void)pTemplate;
	(void)ulAttributeCount;
	(void)pAssociatedData;
	(void)ulAssociatedDataLen;
	(void)phKey;

	return CKR_FUNCTION_NOT_SUPPORTED;
}

/**
 * C_DeriveKey() - Derives a secret key from a base key.
 * @hSession: [in] The session's handle.
 * @pMechanism: [in] Pointer to the key derivation mechanism.
 * @hBaseKey: [in] Handle of the base key.
 * @pTemplate: [in] Pointer to the template attributes for the new key.
 * @ulAttributeCount: [in] Number of attributes in the template.
 * @phKey: [out] Pointer to the location that receives the handle of the derived
 *               key.
 *
 * This function derives a secret key from a base key, creating a new key
 * object.
 *
 * The class CKA_CLASS attribute is not needed as well, if specified and not
 * CKO_PUBLIC_KEY or CKO_PRIVATE_KEY in the respective Public and Private
 * template, the function returns CKR_TEMPLATE_INCONSISTENT error.
 *
 * If the derived key type is a supported key derivation type, the function
 * returns CKR_TEMPLATE_INCONSISTENT errro.
 *
 * Return:
 *  - CKR_OK:
 *      Success.
 *  - CKR_SESSION_HANDLE_INVALID:
 *      The session handle is not valid.
 *  - CKR_KEY_HANDLE_INVALID:
 *      The @hBaseKey is not valid.
 *  - CKR_ARGUMENTS_BAD:
 *      - The @pMechanism is NULL.
 *      - If the mechanism is not CKM_TLS12_KEY_AND_MAC_DERIVE and @phKey is
 *        NULL.
 *  - CKR_TEMPLATE_INCOMPLETE:
 *      The @pTemplate and @ulCount is incomplete or inconsistent.
 *  - CKR_TEMPLATE_INCONSISTENT:
 *      One of the template's attribute type must not be defined.
 *  - CKR_ATTRIBUTE_READ_ONLY:
 *      One attribute is read only
 *  - CKR_ATTRIBUTE_VALUE_INVALID:
 *      One of the template's attribute value is not valid.
 *  - CKR_USER_NOT_LOGGED_IN:
 *      User must login to create object.
 *  - CKR_SLOT_ID_INVALID:
 *      Slot ID is not valid.
 *  - CKR_MECHANISM_INVALID:
 *      Mechanism not supported.
 *  - CKR_HOST_MEMORY:
 *      Allocation error.
 *  - CKR_SESSION_CLOSED:
 *      Session closed.
 *  - CKR_FUNCTION_FAILED:
 *      Function failure.
 *  - CKR_FUNCTION_CANCELED:
 *      Application callback canceled function.
 *  - CKR_TOKEN_NOT_PRESENT:
 *      Token not present.
 *  - CKR_GENERAL_ERROR:
 *      General error.
 *  - CKR_CRYPTOKI_NOT_INITIALIZED:
 *      The library has not been previously initialized by :c:func:`C_Initialize`.
 *  - Other errors from the underlying implementation.
 */
CK_RV C_DeriveKey(CK_SESSION_HANDLE hSession, CK_MECHANISM_PTR pMechanism,
		  CK_OBJECT_HANDLE hBaseKey, CK_ATTRIBUTE_PTR pTemplate,
		  CK_ULONG ulAttributeCount, CK_OBJECT_HANDLE_PTR phKey)
{
	if (!hSession)
		return CKR_SESSION_HANDLE_INVALID;

	if (!pMechanism)
		return CKR_ARGUMENTS_BAD;

	if (!hBaseKey)
		return CKR_KEY_HANDLE_INVALID;

	if (!pTemplate != !ulAttributeCount)
		return CKR_TEMPLATE_INCOMPLETE;

	return libobj_derive_key(hSession, pMechanism, hBaseKey, pTemplate,
				 ulAttributeCount, phKey);
}

/**
 * C_EncapsulateKey() - Encapsulates a symmetric key using a public key.
 * @hSession: [in] The session's handle.
 * @pMechanism: [in] Pointer to the encapsulation mechanism.
 * @hPublicKey: [in] Handle of the public key.
 * @pTemplate: [in] Pointer to the template attributes for new symmetric key.
 * @ulAttributeCount: [in] Number of attributes in the template.
 * @pCiphertext: [out] Pointer to the location that receives the ciphertext
 *                     needed to decapsulate, or :c:macro:`NULL_PTR` to query
 *                     the ciphertext size.
 * @pulCiphertextLen: [in/out] Pointer to the location that gives the size of
 *                             @pCiphertext buffer, or receives the ciphertext
 *                             length.
 * @phKey: [out] Pointer to the location that receives the handle of the
 *               new key.
 *
 * This function creates a new key object from a public key using the Key
 * Encapsulation Mechanism (KEM) defined by the @pMechanism. The @pCiphertext
 * contains the cipher value of the resulting encapsulation.
 *
 * .. warning::
 *    This function is not supported.
 *
 * Return:
 *  - CKR_FUNCTION_NOT_SUPPORTED:
 *      Function is not supported.
 */
CK_RV C_EncapsulateKey(CK_SESSION_HANDLE hSession, CK_MECHANISM_PTR pMechanism,
		       CK_OBJECT_HANDLE hPublicKey, CK_ATTRIBUTE_PTR pTemplate,
		       CK_ULONG ulAttributeCount, CK_BYTE_PTR pCiphertext,
		       CK_ULONG_PTR pulCiphertextLen,
		       CK_OBJECT_HANDLE_PTR phKey)
{
	(void)hSession;
	(void)pMechanism;
	(void)hPublicKey;
	(void)pTemplate;
	(void)ulAttributeCount;
	(void)pCiphertext;
	(void)pulCiphertextLen;
	(void)phKey;

	return CKR_FUNCTION_NOT_SUPPORTED;
}

/**
 * C_DecapsulateKey() - Decapsulates a symmetric key using a private key.
 * @hSession: [in] The session's handle.
 * @pMechanism: [in] Pointer to the decapsulation mechanism.
 * @hPrivateKey: [in] Handle of the private key.
 * @pTemplate: [in] Pointer to the template attributes for the new key.
 * @ulAttributeCount: [in] Number of attributes in the template.
 * @pCiphertext: [in] Pointer to the ciphertext of the encapsulated key.
 * @ulCiphertextLen: [in] Length of the ciphertext.
 * @phKey: [out] Pointer to the location that receives the handle of the new
 *               key.
 *
 * This function creates a new symmetric key based on the private key and
 * the @pCiphertext using the Key Encapsulation Mechanism (KEM) defined by the
 * @pMechanism.
 *
 * .. waring::
 *    This function is not supported.
 *
 * Return:
 *  - CKR_FUNCTION_NOT_SUPPORTED:
 *      Function is not supported.
 */
CK_RV C_DecapsulateKey(CK_SESSION_HANDLE hSession, CK_MECHANISM_PTR pMechanism,
		       CK_OBJECT_HANDLE hPrivateKey, CK_ATTRIBUTE_PTR pTemplate,
		       CK_ULONG ulAttributeCount, CK_BYTE_PTR pCiphertext,
		       CK_ULONG ulCiphertextLen, CK_OBJECT_HANDLE_PTR phKey)
{
	(void)hSession;
	(void)pMechanism;
	(void)hPrivateKey;
	(void)pTemplate;
	(void)ulAttributeCount;
	(void)pCiphertext;
	(void)ulCiphertextLen;
	(void)phKey;

	return CKR_FUNCTION_NOT_SUPPORTED;
}
