/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright 2026 NXP
 */

#ifndef __SESSION_H__
#define __SESSION_H__

#include <tss2/tss2_mu.h>

#define SMW_SESSION_HANDLE_BASE 0x02000000 /* TPM spec: HMAC/Policy sessions */

/**
 * struct start_auth_session_params_t - Parameters for TPM2_StartAuthSession command.
 * @tpmKey:        Handle to the key used to encrypt the salt. Set to TPM2_RH_NULL
 *                 if no salt encryption is required.
 * @bind:          Handle to the entity providing the authValue for the session.
 *                 Set to TPM2_RH_NULL for an unbound session.
 * @nonceCaller:   Nonce value generated by the caller to prevent replay attacks
 *                 and ensure session uniqueness.
 * @encryptedSalt: Encrypted salt value used to establish the session key.
 *                 Empty when tpmKey is TPM2_RH_NULL.
 * @session_type:  Type of session to be established (TPM2_SE_HMAC for HMAC session,
 *                 TPM2_SE_POLICY for policy session, or TPM2_SE_TRIAL for trial session).
 * @symmetric:     Symmetric algorithm and parameters for parameter encryption/decryption
 *                 in the session.
 * @auth_hash:     Hash algorithm to be used for session authentication computations.
 *
 * This structure contains all input parameters required for the TPM2_StartAuthSession
 * command, which establishes an authorization session with the TPM.
 */
typedef struct {
	TPMI_DH_OBJECT tpmKey;
	TPMI_DH_ENTITY bind;
	TPM2B_NONCE nonceCaller;
	TPM2B_ENCRYPTED_SECRET encryptedSalt;
	TPM2_SE session_type;
	TPMT_SYM_DEF symmetric;
	TPMI_ALG_HASH auth_hash;
} start_auth_session_params_t;

#endif /* __SESSION_H__ */
