// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2023-2025 NXP
 */

#include "smw_status.h"

#include "global.h"
#include "debug.h"
#include "utils.h"
#include "subsystems.h"
#include "aead.h"
#include "common.h"

#define MAX_IV_LEN  12
#define ELE_TAG_LEN 16

#define AEAD_ALGO(_key_type_id, _aead_mode_id)                                 \
	{                                                                      \
		.key_type_id = SMW_CONFIG_KEY_TYPE_ID_##_key_type_id,          \
		.aead_mode_id = SMW_CONFIG_AEAD_MODE_ID_##_aead_mode_id,       \
		.aead_algo = HSM_AEAD_ALGO_##_aead_mode_id                     \
	}

static const struct {
	enum smw_config_key_type_id key_type_id;
	enum smw_config_aead_mode_id aead_mode_id;
	hsm_op_auth_enc_algo_t aead_algo;
} aead_algos[] = { AEAD_ALGO(AES, CCM), AEAD_ALGO(AES, GCM),
		   AEAD_ALGO(AES, CHACHA20_POLY1305) };

static int set_aead_algo(enum smw_config_key_type_id key_type_id,
			 enum smw_config_aead_mode_id aead_mode_id,
			 hsm_op_auth_enc_algo_t *aead_algo)
{
	int status = SMW_STATUS_OPERATION_NOT_SUPPORTED;
	unsigned int i = 0;

	for (; i < ARRAY_SIZE(aead_algos); i++) {
		if (key_type_id == aead_algos[i].key_type_id &&
		    aead_mode_id == aead_algos[i].aead_mode_id) {
			*aead_algo = aead_algos[i].aead_algo;
			status = SMW_STATUS_OK;
			break;
		}
	}

	SMW_DBG_PRINTF(VERBOSE, "%s returned %d\n", __func__, status);
	return status;
}

#define AEAD_FLAG(_op_type_id)                                                 \
	{                                                                      \
		.smw_op_type_id = SMW_CONFIG_AEAD_OP_TYPE_ID_##_op_type_id,    \
		.ele_flags = HSM_AUTH_ENC_FLAGS_##_op_type_id                  \
	}

static const struct {
	enum smw_config_aead_op_type_id smw_op_type_id;
	hsm_op_auth_enc_flags_t ele_flags;
} aead_flags[] = { AEAD_FLAG(ENCRYPT), AEAD_FLAG(DECRYPT) };

static int set_aead_flags(struct smw_crypto_aead_args *aead_args,
			  hsm_op_auth_enc_new_flags_t *ele_flags)
{
	int status = SMW_STATUS_OPERATION_NOT_SUPPORTED;
	unsigned int i = 0;

	*ele_flags |= HSM_AUTH_ENC_FLAGS_ONE_SHOT;

	for (; i < ARRAY_SIZE(aead_flags); i++) {
		if (aead_args->op_type_id != aead_flags[i].smw_op_type_id)
			continue;

		*ele_flags |= aead_flags[i].ele_flags;

		if (aead_args->op_type_id !=
			    SMW_CONFIG_AEAD_OP_TYPE_ID_ENCRYPT ||
		    aead_args->mode_id != SMW_CONFIG_AEAD_MODE_ID_GCM) {
			status = SMW_STATUS_OK;
			break;
		}

		if (smw_crypto_get_aead_user_iv_len(aead_args) < MAX_IV_LEN) {
			if (smw_crypto_get_aead_iv_len(aead_args) <
			    MAX_IV_LEN) {
				status = SMW_STATUS_INVALID_IV_SIZE;
				break;
			}
			if (!smw_crypto_get_aead_user_iv_len(aead_args))
				*ele_flags |=
					HSM_AUTH_ENC_FLAGS_GENERATE_FULL_IV;
			else
				*ele_flags |=
					HSM_AUTH_ENC_FLAGS_GENERATE_COUNTER_IV;
		} else if (smw_crypto_get_aead_user_iv_len(aead_args) !=
			   MAX_IV_LEN) {
			status = SMW_STATUS_INVALID_IV_SIZE;
			break;
		}

		status = SMW_STATUS_OK;
		break;
	}

	SMW_DBG_PRINTF(VERBOSE, "%s returned %d\n", __func__, status);
	return status;
}

static void set_all_outputs_length(struct smw_crypto_aead_args *args,
				   unsigned int output_len)
{
	if (args->op_type_id == SMW_CONFIG_AEAD_OP_TYPE_ID_ENCRYPT) {
		smw_crypto_set_aead_output_iv_len(args, MAX_IV_LEN);
		smw_crypto_set_aead_tag_len(args, ELE_TAG_LEN);
	}

	smw_crypto_set_aead_output_len(args, output_len);
}

/**
 * set_output_iv() - Copy the IV buffer to output_iv
 * @args: Pointer to internal AEAD arguments
 * @op_args: Pointer to ELE AEAD operation arguments
 *
 * IV generated by user (iv_len = 12):
 * Copy the IV buffer from user IV buffer to output_iv field.
 *
 * IV generated (partially or entirely) by FW (iv_len = 0 or 4):
 * Copy the IV buffer from @op_args->iv_out buffer to output_iv field.
 *
 * Return:
 * SMW_STATUS_OK                 - Success
 * SMW_STATUS_SUBSYSTEM_FAILURE  - Subsystem don't return IV buffer
 */
static int set_output_iv(struct smw_crypto_aead_args *args,
			 op_auth_enc_new_args_t *op_args)
{
	int status = SMW_STATUS_OK;

	unsigned int iv_len = smw_crypto_get_aead_user_iv_len(args);
	unsigned char *output_iv = smw_crypto_get_aead_output_iv(args);
	unsigned char *iv = smw_crypto_get_aead_user_iv(args);

	if (args->op_type_id == SMW_CONFIG_AEAD_OP_TYPE_ID_DECRYPT)
		return status;

	if (output_iv) {
		if (iv_len < MAX_IV_LEN) {
			if (op_args->iv_out)
				SMW_UTILS_MEMCPY(output_iv, op_args->iv_out,
						 MAX_IV_LEN);
			else
				status = SMW_STATUS_SUBSYSTEM_FAILURE;
		} else if (iv) {
			SMW_UTILS_MEMCPY(output_iv, iv, MAX_IV_LEN);
		}
	}

	return status;
}

/**
 * set_output_length() - Set the output buffer length
 * @args: Pointer to internal AEAD arguments
 *
 * Sets the output buffer length based on input buffer length and tag length.
 * Additionally, sets the IV and tag lengths for AEAD encryption operation.
 *
 * Return:
 * SMW_STATUS_OK            - Success
 * SMW_STATUS_INVALID_PARAM - Invalid argument parameter
 */
static int set_output_length(struct smw_crypto_aead_args *aead_args)
{
	int status = SMW_STATUS_INVALID_PARAM;

	unsigned int output_len = smw_crypto_get_aead_input_len(aead_args);

	if (aead_args->op_type_id == SMW_CONFIG_AEAD_OP_TYPE_ID_ENCRYPT) {
		if (!smw_crypto_is_aead_tag_field_set(aead_args)) {
			if (INC_OVERFLOW(output_len, ELE_TAG_LEN))
				goto end;
		}

	} else {
		if (!smw_crypto_is_aead_tag_field_set(aead_args)) {
			if (DEC_OVERFLOW(output_len, ELE_TAG_LEN))
				goto end;
		}
	}

	status = SMW_STATUS_OK;

	set_all_outputs_length(aead_args, output_len);

end:
	SMW_DBG_PRINTF(VERBOSE, "%s returned with output length = %u\n",
		       __func__, output_len);
	return status;
}

static int get_private_key_buffer(op_auth_enc_new_args_t *op_args,
				  struct smw_keymgr_descriptor *key_desc)
{
	int status = SMW_STATUS_INVALID_PARAM;

	unsigned int private_buf_len = smw_keymgr_get_private_length(key_desc);
	unsigned char *private_buffer = smw_keymgr_get_private_data(key_desc);
	unsigned int hex_private_len = 0;

	if (!private_buf_len || !private_buffer)
		goto end;

	status = smw_keymgr_set_hex_key_buffer(key_desc->format_id,
					       private_buffer, private_buf_len,
					       &op_args->key, &hex_private_len);
	if (status != SMW_STATUS_OK)
		goto end;

	if (SET_OVERFLOW(hex_private_len, op_args->key_size)) {
		status = SMW_STATUS_INVALID_PARAM;
		goto end;
	}

end:
	return status;
}

static int set_key(struct smw_crypto_aead_args *aead_args,
		   op_auth_enc_new_args_t *op_args)
{
	int status = SMW_STATUS_OK;

	struct smw_keymgr_descriptor *key_desc = &aead_args->key_desc;
	struct smw_keymgr_identifier *key_identifier = &key_desc->identifier;
	hsm_key_type_t ele_key_type = (hsm_key_type_t)0;

	if (key_identifier->s_id) {
		op_args->key_id = key_identifier->s_id;
	} else {
		/* AEAD using plaintext key buffer */
		op_args->flags = HSM_AUTH_ENC_FLAGS_PLAINTEXT_KEY;

		status = ele_get_key_type(key_identifier->type_id,
					  &ele_key_type);
		if (status != SMW_STATUS_OK)
			goto end;

		op_args->key_type = ele_key_type;

		status = get_private_key_buffer(op_args, key_desc);
	}

end:
	return status;
}

/**
 * get_input_data_len() - Return the length of the input data buffer
 * @args: Pointer to internal AEAD argument structure
 * @input_data_length: Pointer to hold the input data buffer length
 *
 * For encryption operation, it returns the length of the input data.
 * For decryption operation, it returns length of the ciphertext (excluding tag
 * length, if tag is part of the output buffer)
 *
 * Return:
 * SMW_STATUS_OK            - Success
 * SMW_STATUS_INVALID_PARAM - Invalid argument parameter
 */
static unsigned int get_input_data_len(struct smw_crypto_aead_args *args,
				       unsigned int *input_data_length)
{
	int status = SMW_STATUS_OK;

	*input_data_length = smw_crypto_get_aead_input_len(args);

	if (args->op_type_id == SMW_CONFIG_AEAD_OP_TYPE_ID_DECRYPT) {
		if (!smw_crypto_is_aead_tag_field_set(args)) {
			if (DEC_OVERFLOW(*input_data_length,
					 smw_crypto_get_aead_tag_len(args)))
				status = SMW_STATUS_INVALID_PARAM;
		}
	}

	SMW_DBG_PRINTF(VERBOSE, "%s returned with input length = %u\n",
		       __func__, *input_data_length);
	return status;
}

/**
 * get_output_data_len() - Return the length of the output data buffer
 * @args: Pointer to internal AEAD arguments
 * @output_data_length: Pointer to hold the output data buffer length
 *
 * For encryption operation, it returns length of the ciphertext (excluding tag
 * length, if tag is part of the output buffer)
 * For decryption operation, it returns the length of the output data buffer.
 *
 * Return:
 * SMW_STATUS_OK
 * SMW_STATUS_INVALID_PARAM
 */
static int get_output_data_len(struct smw_crypto_aead_args *args,
			       unsigned int *output_data_length)
{
	int status = SMW_STATUS_OK;

	*output_data_length = smw_crypto_get_aead_output_len(args);

	if (args->op_type_id == SMW_CONFIG_AEAD_OP_TYPE_ID_ENCRYPT) {
		if (!smw_crypto_is_aead_tag_field_set(args)) {
			if (DEC_OVERFLOW(*output_data_length,
					 smw_crypto_get_aead_tag_len(args)))
				status = SMW_STATUS_OUTPUT_TOO_SHORT;
		}
	}

	SMW_DBG_PRINTF(VERBOSE, "%s returned with output length = %u\n",
		       __func__, *output_data_length);

	return status;
}

static int aead(struct hdl *hdl, void *args)
{
	int status = SMW_STATUS_INVALID_IV_SIZE;

	hsm_err_t err = HSM_NO_ERROR;
	op_auth_enc_new_args_t op_args = { 0 };

	enum smw_config_key_type_id key_type_id = 0;
	struct smw_crypto_aead_args *aead_args = args;
	struct smw_keymgr_descriptor *key_desc = &aead_args->key_desc;
	struct smw_keymgr_identifier *key_identifier = &key_desc->identifier;

	unsigned int output_length = 0;
	bool is_encrypt_op = false;

	SMW_DBG_TRACE_FUNCTION_CALL;

	if ((aead_args->mode_id == SMW_CONFIG_AEAD_MODE_ID_CCM ||
	     aead_args->mode_id == SMW_CONFIG_AEAD_MODE_ID_CHACHA20_POLY1305) &&
	    smw_crypto_get_aead_user_iv_len(aead_args) != MAX_IV_LEN) {
		goto end;
	}

	/*
	 * For ELE subsystem, tag length must be 16 Bytes.
	 * For encryption operation, if tag length < ELE_TAG_LEN, set the required
	 * output buffer lengths and return SMW_STATUS_OUTPUT_TOO_SHORT.
	 */
	if (smw_crypto_get_aead_tag_len(aead_args) < ELE_TAG_LEN) {
		(void)set_output_length(aead_args);
		status = SMW_STATUS_OUTPUT_TOO_SHORT;
		goto end;
	}

	if (aead_args->op_type_id == SMW_CONFIG_AEAD_OP_TYPE_ID_ENCRYPT)
		is_encrypt_op = true;

	op_args.iv_in = smw_crypto_get_aead_user_iv(aead_args);

	if (SET_OVERFLOW(smw_crypto_get_aead_user_iv_len(aead_args),
			 op_args.iv_size)) {
		status = SMW_STATUS_INVALID_PARAM;
		goto end;
	}

	key_type_id = key_identifier->type_id;

	/* Get ELE algorithm */
	status = set_aead_algo(key_type_id, aead_args->mode_id,
			       &op_args.ae_algo);
	if (status != SMW_STATUS_OK)
		goto end;

	/* Set the key parameters */
	status = set_key(aead_args, &op_args);
	if (status != SMW_STATUS_OK)
		goto end;

	/* Set ELE AEAD flags */
	status = set_aead_flags(aead_args, &op_args.flags);
	if (status != SMW_STATUS_OK)
		goto end;

	/* Get output length feature */
	if (!smw_crypto_get_aead_output(aead_args)) {
		status = set_output_length(aead_args);
		goto end;
	}

	status = get_output_data_len(aead_args, &op_args.output_size);
	if (status == SMW_STATUS_OUTPUT_TOO_SHORT) {
		(void)set_output_length(aead_args);
		goto end;
	}

	op_args.output = smw_crypto_get_aead_output(aead_args);

	status = get_input_data_len(aead_args, &op_args.input_size);
	if (status != SMW_STATUS_OK)
		goto end;

	op_args.input = smw_crypto_get_aead_input(aead_args);

	op_args.aad = smw_crypto_get_aead_aad(aead_args);

	if (SET_OVERFLOW(smw_crypto_get_aead_aad_len(aead_args),
			 op_args.aad_size)) {
		status = SMW_STATUS_INVALID_PARAM;
		goto end;
	}

	op_args.tag = smw_crypto_get_aead_tag(aead_args);

	if (SET_OVERFLOW(smw_crypto_get_aead_tag_len(aead_args),
			 op_args.tag_size)) {
		status = SMW_STATUS_INVALID_PARAM;
		goto end;
	}

	SMW_DBG_PRINTF(VERBOSE,
		       "[%s (%d)] Call hsm_do_auth_enc_new()\n"
		       "op_auth_enc_new_args_t\n"
		       "    key_identifier: 0x%08X\n"
		       "    key buffer\n"
		       "      - buffer: %p\n"
		       "      - key size: %d\n"
		       "      - type: 0x%08X\n"
		       "    algo: 0x%08X\n"
		       "    flags: 0x%X\n"
		       "    IV_in\n"
		       "      - buffer: %p\n"
		       "      - size: %d\n"
		       "    IV_out\n"
		       "      - buffer: %p\n"
		       "      - size: %d\n"
		       "    Tag\n"
		       "      - buffer: %p\n"
		       "      - size: %d\n"
		       "    AAD\n"
		       "      - buffer: %p\n"
		       "      - size: %d\n"
		       "    Input\n"
		       "       - buffer: %p\n"
		       "       - size: %d\n"
		       "    Output\n"
		       "       - buffer: %p\n"
		       "       - size: %d\n",
		       __func__, __LINE__, op_args.key_id, op_args.key,
		       op_args.key_size, op_args.key_type, op_args.ae_algo,
		       op_args.flags, op_args.iv_in, op_args.iv_size,
		       op_args.iv_out, op_args.iv_size, op_args.tag,
		       op_args.tag_size, op_args.aad, op_args.aad_size,
		       op_args.input, op_args.input_size, op_args.output,
		       op_args.output_size);

	err = hsm_do_auth_enc_new(hdl->key_store, &op_args);

	SMW_DBG_PRINTF(DEBUG,
		       "hsm_do_auth_enc_new returned %d, verify_status = 0x%x\n",
		       err, op_args.verify_status);

	SMW_DBG_PRINTF(DEBUG, "Expected output size = %u\n",
		       op_args.exp_output_size);

	status = ele_convert_err(err);
	if (status != SMW_STATUS_OK && status != SMW_STATUS_OUTPUT_TOO_SHORT)
		goto end;

	/*
	 * If the tag is invalid, verification status is set to
	 * HSM_AEAD_VERIFICATION_STATUS_FAILURE but the API response indicator
	 * returns HSM_NO_ERROR.
	 */
	if (!is_encrypt_op &&
	    op_args.verify_status == HSM_AEAD_VERIFICATION_STATUS_FAILURE) {
		status = SMW_STATUS_SIGNATURE_INVALID;
		goto end;
	}

	if (SET_OVERFLOW(op_args.exp_output_size, output_length)) {
		status = SMW_STATUS_OPERATION_FAILURE;
		goto end;
	}

	smw_crypto_set_aead_output_len(aead_args, output_length);

	if (is_encrypt_op) {
		if (!smw_crypto_is_aead_tag_field_set(args)) {
			if (INC_OVERFLOW(output_length, ELE_TAG_LEN)) {
				status = SMW_STATUS_OPERATION_FAILURE;
				goto end;
			}
		}

		if (status == SMW_STATUS_OK)
			status = set_output_iv(aead_args, &op_args);

		if (status == SMW_STATUS_OK)
			set_all_outputs_length(aead_args, output_length);
	}

end:
	if (key_desc->format_id == SMW_KEYMGR_FORMAT_ID_BASE64 && op_args.key)
		SMW_UTILS_FREE(op_args.key);

	/*
	 * SE lib allocates op_args.iv_out and it should be released after the
	 * operation is performed.
	 */
	if (op_args.iv_out)
		SMW_UTILS_FREE(op_args.iv_out);

	SMW_DBG_PRINTF(VERBOSE, "%s returned %d\n", __func__, status);
	return status;
}

bool ele_aead_handle(struct hdl *hdl, enum operation_id operation_id,
		     void *args, int *status)
{
	SMW_DBG_PRINTF(VERBOSE, "Executing %s\n", __func__);

	switch (operation_id) {
	case OPERATION_ID_AEAD:
		*status = aead(hdl, args);
		break;

	default:
		return false;
	}

	return true;
}
