// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2023 NXP
 */

#include "smw_status.h"

#include "global.h"
#include "debug.h"
#include "utils.h"
#include "subsystems.h"
#include "aead.h"
#include "common.h"

#define MAX_IV_LEN  12
#define ELE_TAG_LEN 16

#define AEAD_ALGO(_key_type_id, _aead_mode_id)                                 \
	{                                                                      \
		.key_type_id = SMW_CONFIG_KEY_TYPE_ID_##_key_type_id,          \
		.aead_mode_id = SMW_CONFIG_AEAD_MODE_ID_##_aead_mode_id,       \
		.aead_algo = HSM_AEAD_ALGO_##_aead_mode_id                     \
	}

static const struct {
	enum smw_config_key_type_id key_type_id;
	enum smw_config_aead_mode_id aead_mode_id;
	hsm_op_auth_enc_algo_t aead_algo;
} aead_algos[] = { AEAD_ALGO(AES, CCM), AEAD_ALGO(AES, GCM) };

static int set_aead_algo(enum smw_config_key_type_id key_type_id,
			 enum smw_config_aead_mode_id aead_mode_id,
			 hsm_op_auth_enc_algo_t *aead_algo)
{
	int status = SMW_STATUS_OPERATION_NOT_SUPPORTED;
	unsigned int i = 0;

	for (; i < ARRAY_SIZE(aead_algos); i++) {
		if (key_type_id == aead_algos[i].key_type_id &&
		    aead_mode_id == aead_algos[i].aead_mode_id) {
			*aead_algo = aead_algos[i].aead_algo;
			status = SMW_STATUS_OK;
			break;
		}
	}

	SMW_DBG_PRINTF(VERBOSE, "%s returned %d\n", __func__, status);
	return status;
}

#define AEAD_FLAG(_op_type_id)                                                 \
	{                                                                      \
		.smw_op_type_id = SMW_CONFIG_AEAD_OP_ID_##_op_type_id,         \
		.ele_flags = HSM_AUTH_ENC_FLAGS_##_op_type_id                  \
	}

static const struct {
	enum smw_config_aead_op_type_id smw_op_type_id;
	hsm_op_auth_enc_flags_t ele_flags;
} aead_flags[] = { AEAD_FLAG(ENCRYPT), AEAD_FLAG(DECRYPT) };

static int set_aead_flags(struct smw_crypto_aead_args *aead_args,
			  hsm_op_auth_enc_flags_t *ele_flags)
{
	int status = SMW_STATUS_OPERATION_NOT_SUPPORTED;
	unsigned int i = 0;

	for (; i < ARRAY_SIZE(aead_flags); i++) {
		if (aead_args->op_id != aead_flags[i].smw_op_type_id)
			continue;

		*ele_flags = aead_flags[i].ele_flags;

		if (aead_args->op_id == SMW_CONFIG_AEAD_OP_ID_ENCRYPT &&
		    aead_args->mode_id == SMW_CONFIG_AEAD_MODE_ID_GCM) {
			if (!smw_crypto_get_iv_len(aead_args))
				*ele_flags |=
					HSM_AUTH_ENC_FLAGS_GENERATE_FULL_IV;
			else if (smw_crypto_get_iv_len(aead_args) != MAX_IV_LEN)
				*ele_flags |=
					HSM_AUTH_ENC_FLAGS_GENERATE_COUNTER_IV;
		}

		status = SMW_STATUS_OK;
		break;
	}

	SMW_DBG_PRINTF(VERBOSE, "%s returned %d\n", __func__, status);
	return status;
}

/**
 * get_ele_expected_encr_output_len() - Return the ELE expected output length
 * @args: Pointer to internal AEAD arguments
 * @length: Pointer to output buffer length
 *
 * This function returns the ELE expected output buffer length for encryption
 * operation
 *
 * Encryption:
 * GCM with IV generated (partially or entirely) by FW (iv_len = 4 or 0):
 * output length = ciphertext len + tag len (16 bytes) + IV len (12 bytes)
 *
 * GCM with IV generated by user or CCM mode (iv_len = 12):
 * output length = ciphertext length + tag len(16 bytes)
 *
 * Return:
 * SMW_STATUS_OK		- Success
 * SMW_STATUS_INVALID_PARAM	- Invalid argument parameter
 */
static int
get_ele_expected_encr_output_len(struct smw_crypto_aead_args *aead_args,
				 unsigned int *length)
{
	int status = SMW_STATUS_INVALID_PARAM;

	unsigned int iv_len = smw_crypto_get_iv_len(aead_args);
	unsigned int tag_len = smw_crypto_get_tag_len(aead_args);

	*length = smw_crypto_get_input_len(aead_args);

	if (!INC_OVERFLOW(*length, tag_len)) {
		if (aead_args->mode_id == SMW_CONFIG_AEAD_MODE_ID_GCM &&
		    iv_len < MAX_IV_LEN) {
			if (INC_OVERFLOW(*length, MAX_IV_LEN))
				goto end;
		}

		status = SMW_STATUS_OK;
	}

end:
	SMW_DBG_PRINTF(VERBOSE, "%s returned %d with output length = %u\n",
		       __func__, status, *length);
	return status;
}

static void set_all_outputs_length(struct smw_crypto_aead_args *args,
				   unsigned int *output_len)
{
	if (args->op_id == SMW_CONFIG_AEAD_OP_ID_ENCRYPT) {
		smw_crypto_set_output_iv_len(args, MAX_IV_LEN);
		smw_crypto_set_tag_len(args, ELE_TAG_LEN);
	}

	smw_crypto_set_output_len(args, *output_len);
}

/**
 * set_output_iv() - Copy the IV buffer to output_iv
 * @args: Pointer to internal AEAD arguments
 * @iv_start_index: Starting index of the IV in the output buffer
 * @op_args: Pointer to ELE AEAD operation arguments
 *
 * IV generated by user (iv_len = 12):
 * Copy the IV buffer from user IV buffer to output_iv field.
 *
 * IV generated (partially or entirely) by FW (iv_len = 0 or 4):
 * Copy the IV buffer from output buffer to output_iv field.
 *
 * Return:
 * None
 */
static void set_output_iv(struct smw_crypto_aead_args *args,
			  unsigned int iv_start_index,
			  op_auth_enc_args_t *op_args)
{
	unsigned int iv_len = smw_crypto_get_iv_len(args);
	unsigned char *output_iv = smw_crypto_get_output_iv(args);
	unsigned char *iv = smw_crypto_get_iv(args);

	if (output_iv) {
		if (iv_len < MAX_IV_LEN)
			SMW_UTILS_MEMCPY(output_iv,
					 &op_args->output[iv_start_index],
					 MAX_IV_LEN);
		else if (iv)
			SMW_UTILS_MEMCPY(output_iv, iv, MAX_IV_LEN);
	}
}

/**
 * set_encryption_io_params() - Set input and output params
 * @aead_args: Pointer to internal AEAD arguments
 * @op_args: Pointer to ELE AEAD operation arguments
 * @resized_output: Double pointer to resized output buffer
 *
 * This function sets ELE AEAD arguments input, input_size, output and
 * output_size for AEAD encryption operation.
 *
 * This function allocates memory to resized_output, if the user output buffer
 * length is less than ELE expected output length (output buffer length +
 * tag length (if applicable) + IV length (if applicable)).
 *
 * resized_output is released once the AEAD operation is performed.
 *
 * Return:
 * SMW_STATUS_OK		- Success
 * SMW_STATUS_INVALID_PARAM	- Invalid argument parameter
 * SMW_STATUS_OUTPUT_TOO_SHORT - Ouptut buffer is too short
 * SMW_STATUS_ALLOC_FAILURE	- Memory allocation failure
 */
static int set_encryption_io_params(struct smw_crypto_aead_args *aead_args,
				    op_auth_enc_args_t *op_args,
				    unsigned char **resized_output)
{
	int status = SMW_STATUS_OK;

	unsigned int ele_expected_output_len = 0;
	unsigned int output_len = smw_crypto_get_output_len(aead_args);
	bool dedicated_tag_field_set = smw_crypto_is_tag_field_set(aead_args);
	unsigned int tag_len = smw_crypto_get_tag_len(aead_args);
	unsigned int total_user_output_len = output_len;
	unsigned int exp_total_user_output_len =
		smw_crypto_get_input_len(aead_args);

	status = get_ele_expected_encr_output_len(aead_args,
						  &ele_expected_output_len);
	if (status != SMW_STATUS_OK)
		goto end;

	/*
	 * total_user_output_len is the total user output length.
	 * total user output length = user output length + tag
	 * length (if applicable).
	 * exp_total_user_output_len is the expected total user output length.
	 * expected total user output length = user input length +
	 * tag length (if applicable).
	 */
	if (dedicated_tag_field_set) {
		if (INC_OVERFLOW(total_user_output_len, tag_len)) {
			status = SMW_STATUS_INVALID_PARAM;
			goto end;
		}

		if (INC_OVERFLOW(exp_total_user_output_len, tag_len)) {
			status = SMW_STATUS_INVALID_PARAM;
			goto end;
		}
	}

	if (total_user_output_len < exp_total_user_output_len) {
		status = SMW_STATUS_OUTPUT_TOO_SHORT;
		goto end;
	}

	if (output_len < ele_expected_output_len) {
		*resized_output = SMW_UTILS_MALLOC(ele_expected_output_len *
						   sizeof(**resized_output));
		if (!*resized_output) {
			status = SMW_STATUS_ALLOC_FAILURE;
			goto end;
		}

		op_args->output = *resized_output;
		output_len = ele_expected_output_len;

	} else {
		op_args->output = smw_crypto_get_output(aead_args);
	}

	if (SET_OVERFLOW(output_len, op_args->output_size)) {
		status = SMW_STATUS_INVALID_PARAM;
		goto end;
	}

	op_args->input = smw_crypto_get_input(aead_args);

	if (SET_OVERFLOW(smw_crypto_get_input_len(aead_args),
			 op_args->input_size))
		status = SMW_STATUS_INVALID_PARAM;

end:
	SMW_DBG_PRINTF(VERBOSE, "%s returned %d\n", __func__, status);
	return status;
}

/**
 * set_decryption_io_params() - Set input and output params
 * @aead_args: Pointer to internal AEAD arguments
 * @op_args: Pointer to ELE AEAD operation arguments
 * @resized_input: Double pointer to resized input buffer
 *
 * This function sets ELE AEAD arguments input, input_size, output
 * and output_size for AEAD decryption operation.
 *
 * This function allocates memory to resized_input, if the
 * tag is set in the dedicated tag field. In this case, input
 * buffer and tag buffer will be copied to resized_input.
 *
 * resized_input is released once the AEAD operation is performed.
 *
 * Return:
 * SMW_STATUS_OK		- Success
 * SMW_STATUS_INVALID_PARAM	- Invalid argument parameter
 * SMW_STATUS_OUTPUT_TOO_SHORT - Ouptut buffer is too short
 * SMW_STATUS_ALLOC_FAILURE	- Memory allocation failure
 */
static int set_decryption_io_params(struct smw_crypto_aead_args *aead_args,
				    op_auth_enc_args_t *op_args,
				    unsigned char **resized_input)
{
	int status = SMW_STATUS_INVALID_PARAM;

	unsigned int input_len = smw_crypto_get_input_len(aead_args);
	unsigned int tag_len = smw_crypto_get_tag_len(aead_args);
	unsigned char *input = smw_crypto_get_input(aead_args);
	unsigned int ele_expected_input_len = input_len;
	unsigned int ele_expected_output_len = input_len;
	bool dedicated_tag_field_set = smw_crypto_is_tag_field_set(aead_args);

	if (!input_len || !input)
		goto end;

	if (!dedicated_tag_field_set) {
		if (DEC_OVERFLOW(ele_expected_output_len, tag_len))
			goto end;
	}

	if (smw_crypto_get_output_len(aead_args) < ele_expected_output_len) {
		status = SMW_STATUS_OUTPUT_TOO_SHORT;
		goto end;
	}

	op_args->output = smw_crypto_get_output(aead_args);

	if (SET_OVERFLOW(smw_crypto_get_output_len(aead_args),
			 op_args->output_size))
		goto end;

	if (dedicated_tag_field_set) {
		if (INC_OVERFLOW(ele_expected_input_len, tag_len))
			goto end;

		*resized_input = SMW_UTILS_MALLOC(ele_expected_input_len *
						  sizeof(**resized_input));
		if (!*resized_input) {
			status = SMW_STATUS_ALLOC_FAILURE;
			goto end;
		}

		SMW_UTILS_MEMCPY(*resized_input, input, input_len);

		if (smw_crypto_get_tag(aead_args) && tag_len)
			SMW_UTILS_MEMCPY(*resized_input + input_len,
					 smw_crypto_get_tag(aead_args),
					 tag_len);
		else
			goto end;

		op_args->input = *resized_input;
		input_len = ele_expected_input_len;

	} else {
		op_args->input = smw_crypto_get_input(aead_args);
	}

	if (SET_OVERFLOW(input_len, op_args->input_size))
		goto end;

	status = SMW_STATUS_OK;

end:
	SMW_DBG_PRINTF(VERBOSE, "%s returned %d\n", __func__, status);
	return status;
}

/**
 * set_user_encr_outputs_len() - Calculate output buffers length
 * @args: Pointer to internal AEAD arguments
 * @output_len: Pointer to output buffer length
 *
 * @output_len initially points to the expected output length received from FW.
 * This function then modifies the value pointed to by @output_len
 * to user output length after performing calculations based on IV and tag.
 *
 * Return:
 * SMW_STATUS_OK		- Success
 * SMW_STATUS_OPERATION_FAILURE	- Operation failed
 */
static int set_user_encr_outputs_len(struct smw_crypto_aead_args *args,
				     unsigned int *output_len)
{
	int status = SMW_STATUS_OPERATION_FAILURE;

	if (smw_crypto_get_iv_len(args) < MAX_IV_LEN) {
		if (DEC_OVERFLOW(*output_len, MAX_IV_LEN))
			goto end;
	}

	if (smw_crypto_is_tag_field_set(args)) {
		if (DEC_OVERFLOW(*output_len, smw_crypto_get_tag_len(args)))
			goto end;
	}

	set_all_outputs_length(args, output_len);
	status = SMW_STATUS_OK;

end:
	SMW_DBG_PRINTF(VERBOSE, "%s returned %d\n", __func__, status);
	return status;
}

/**
 * copy_buffers_post_encr() - Copy output, tag, IV buffers from output buffer
 * @op_args: Pointer to ELE AEAD arguments
 * @args: Pointer to internal AEAD arguments
 * @output_len: Pointer to output buffer length
 * @resized_output: Pointer to resized output buffer
 *
 * @output_len initially points to the expected output length received from FW
 * as input. Update the value pointed to by @output_len to user output length
 * after performing calculations based on IV and tag.
 *
 * Copy the output IV buffer, tag(if applicable) and output
 * buffer(if applicable) from op_args->output if the operation is AEAD
 * encryption.
 *
 * Return:
 * SMW_STATUS_OK		- Success
 * SMW_STATUS_OPERATION_FAILURE	- Operation failed
 */
static int copy_buffers_post_encr(op_auth_enc_args_t *op_args,
				  struct smw_crypto_aead_args *args,
				  unsigned int *output_len,
				  unsigned char *resized_output)
{
	int status = SMW_STATUS_OK;

	bool dedicated_tag_field_set = smw_crypto_is_tag_field_set(args);
	unsigned int tag_len = smw_crypto_get_tag_len(args);
	unsigned int iv_start_index = 0;
	unsigned char *tag = smw_crypto_get_tag(args);
	unsigned char *output = smw_crypto_get_output(args);

	status = set_user_encr_outputs_len(args, output_len);
	if (status != SMW_STATUS_OK)
		goto end;

	if (smw_crypto_get_iv_len(args) < MAX_IV_LEN) {
		iv_start_index = *output_len;

		if (dedicated_tag_field_set) {
			if (INC_OVERFLOW(iv_start_index, tag_len)) {
				status = SMW_STATUS_OPERATION_FAILURE;
				goto end;
			}
		}
	}

	set_output_iv(args, iv_start_index, op_args);

	if (dedicated_tag_field_set) {
		if (tag && tag_len) {
			SMW_UTILS_MEMCPY(tag, &op_args->output[*output_len],
					 tag_len);
		} else {
			status = SMW_STATUS_OPERATION_FAILURE;
			goto end;
		}
	}

	if (resized_output) {
		if (output && *output_len) {
			SMW_UTILS_MEMCPY(output, op_args->output, *output_len);
		} else {
			status = SMW_STATUS_OPERATION_FAILURE;
			goto end;
		}
	}

end:
	SMW_DBG_PRINTF(VERBOSE, "%s returned %d\n", __func__, status);
	return status;
}

/**
 * set_output_length() - Set the user output buffer length
 * @args: Pointer to internal AEAD arguments
 *
 * Calculate and set the user output buffer length
 * based on user input buffer length and tag length.
 *
 * Return:
 * SMW_STATUS_OK		- Success
 * SMW_STATUS_INVALID_PARAM	- Invalid argument parameter
 */
static int set_output_length(struct smw_crypto_aead_args *aead_args)
{
	int status = SMW_STATUS_INVALID_PARAM;

	unsigned int output_len = smw_crypto_get_input_len(aead_args);

	if (aead_args->op_id == SMW_CONFIG_AEAD_OP_ID_ENCRYPT) {
		if (!smw_crypto_is_tag_field_set(aead_args)) {
			if (INC_OVERFLOW(output_len, ELE_TAG_LEN))
				goto end;
		}

	} else {
		if (!smw_crypto_is_tag_field_set(aead_args)) {
			if (DEC_OVERFLOW(output_len, ELE_TAG_LEN))
				goto end;
		}
	}

	status = SMW_STATUS_OK;

	set_all_outputs_length(aead_args, &output_len);

end:
	SMW_DBG_PRINTF(VERBOSE, "%s returned with output length = %u\n",
		       __func__, output_len);
	return status;
}

static int aead(struct hdl *hdl, void *args)
{
	int status = SMW_STATUS_OPERATION_NOT_SUPPORTED;

	hsm_err_t err = HSM_NO_ERROR;
	op_auth_enc_args_t op_args = { 0 };

	enum smw_config_key_type_id key_type_id = 0;
	struct smw_crypto_aead_args *aead_args = args;
	struct smw_keymgr_descriptor *key_desc = &aead_args->key_desc;
	struct smw_keymgr_identifier *key_identifier = &key_desc->identifier;

	unsigned char *resized_output = NULL;
	unsigned char *resized_input = NULL;

	unsigned int output_length = 0;
	bool is_encrypt_op = false;

	SMW_DBG_TRACE_FUNCTION_CALL;

	if (key_desc->format_id != SMW_KEYMGR_FORMAT_ID_INVALID) {
		// TODO: first import key, then do authenticated encryption
		// Currently, key import is not supported by ELE
		SMW_DBG_PRINTF(VERBOSE,
			       "%s : key import is not supported by ELE\n",
			       __func__);
		goto end;
	}

	if (aead_args->mode_id == SMW_CONFIG_AEAD_MODE_ID_CCM &&
	    smw_crypto_get_iv_len(aead_args) != MAX_IV_LEN) {
		status = SMW_STATUS_INVALID_PARAM;
		goto end;
	}

	/*
	 * For ELE subsystem, tag length must be 16 Bytes.
	 * For encryption operation, if tag length < ELE_TAG_LEN, set the required
	 * output buffer lengths and return SMW_STATUS_OUTPUT_TOO_SHORT.
	 */
	if (smw_crypto_get_tag_len(aead_args) < ELE_TAG_LEN) {
		(void)set_output_length(aead_args);
		status = SMW_STATUS_OUTPUT_TOO_SHORT;
		goto end;
	}

	if (aead_args->op_id == SMW_CONFIG_AEAD_OP_ID_ENCRYPT)
		is_encrypt_op = true;

	op_args.iv = smw_crypto_get_iv(aead_args);

	if (SET_OVERFLOW(smw_crypto_get_iv_len(aead_args), op_args.iv_size)) {
		status = SMW_STATUS_INVALID_PARAM;
		goto end;
	}

	key_type_id = key_identifier->type_id;

	/* Get ELE algorithm */
	status = set_aead_algo(key_type_id, aead_args->mode_id,
			       &op_args.ae_algo);
	if (status != SMW_STATUS_OK)
		goto end;

	/* Set ELE AEAD flags */
	status = set_aead_flags(aead_args, &op_args.flags);
	if (status != SMW_STATUS_OK)
		goto end;

	op_args.key_identifier = key_identifier->id;

	/* Get output length feature */
	if (!smw_crypto_get_output(aead_args)) {
		status = set_output_length(aead_args);
		goto end;
	}

	if (is_encrypt_op)
		status = set_encryption_io_params(aead_args, &op_args,
						  &resized_output);
	else
		status = set_decryption_io_params(aead_args, &op_args,
						  &resized_input);

	if (status == SMW_STATUS_OUTPUT_TOO_SHORT) {
		(void)set_output_length(aead_args);
		goto end;
	}

	if (status != SMW_STATUS_OK)
		goto end;

	op_args.aad = smw_crypto_get_aad(aead_args);

	if (SET_OVERFLOW(smw_crypto_get_aad_len(aead_args), op_args.aad_size)) {
		status = SMW_STATUS_INVALID_PARAM;
		goto end;
	}

	SMW_DBG_PRINTF(VERBOSE,
		       "[%s (%d)] Call hsm_do_auth_enc()\n"
		       "op_auth_enc_args_t\n"
		       "    key_identifier: 0x%08X\n"
		       "    algo: 0x%08X\n"
		       "    flags: 0x%X\n"
		       "    IV\n"
		       "      - buffer: %p\n"
		       "      - size: %d\n"
		       "    AAD\n"
		       "      - buffer: %p\n"
		       "      - size: %d\n"
		       "    Input\n"
		       "       - buffer: %p\n"
		       "       - size: %d\n"
		       "    Output\n"
		       "       - buffer: %p\n"
		       "       - size: %d\n",
		       __func__, __LINE__, op_args.key_identifier,
		       op_args.ae_algo, op_args.flags, op_args.iv,
		       op_args.iv_size, op_args.aad, op_args.aad_size,
		       op_args.input, op_args.input_size, op_args.output,
		       op_args.output_size);

	err = hsm_do_auth_enc(hdl->key_store, &op_args);

	SMW_DBG_PRINTF(DEBUG, "%s returned %d. expected output size = %u\n",
		       __func__, err, op_args.exp_output_size);

	if (!is_encrypt_op && err == HSM_GENERAL_ERROR)
		/*
		 * Assume ELE returned this error code
		 * because the tag is invalid.
		 */
		status = SMW_STATUS_SIGNATURE_INVALID;
	else
		status = ele_convert_err(err);

	if (!SET_OVERFLOW(op_args.exp_output_size, output_length)) {
		if (!is_encrypt_op) {
			smw_crypto_set_output_len(aead_args, output_length);
		} else {
			if (status == SMW_STATUS_OK && op_args.output)
				status = copy_buffers_post_encr(&op_args,
								aead_args,
								&output_length,
								resized_output);

			else if (status == SMW_STATUS_OUTPUT_TOO_SHORT)
				(void)set_user_encr_outputs_len(aead_args,
								&output_length);
		}

	} else {
		status = SMW_STATUS_OPERATION_FAILURE;
	}

end:

	if (resized_input)
		SMW_UTILS_FREE(resized_input);

	if (resized_output)
		SMW_UTILS_FREE(resized_output);

	SMW_DBG_PRINTF(VERBOSE, "%s returned %d\n", __func__, status);
	return status;
}

bool ele_aead_handle(struct hdl *hdl, enum operation_id operation_id,
		     void *args, int *status)
{
	SMW_DBG_PRINTF(VERBOSE, "Executing %s\n", __func__);

	switch (operation_id) {
	case OPERATION_ID_AEAD:
		*status = aead(hdl, args);
		break;

	default:
		return false;
	}

	return true;
}
