function(add_private_sources target)
  if(BUILD_ZEPHYR)
    zephyr_library_sources(${ARGN})
  else()
    target_sources(${target} PRIVATE ${ARGN})
  endif()
endfunction()

function(add_private_sources_ifdef target cond)
  if(BUILD_ZEPHYR)
    zephyr_library_sources_ifdef(${cond} ${ARGN})
  else()
    target_sources(${target} PRIVATE $<$<BOOL:${cond}>:${ARGN}>)
  endif()
endfunction()

function(add_private_directories target)
  if(BUILD_ZEPHYR)
    zephyr_library_include_directories(${ARGN})
  else()
    target_include_directories(${target} PRIVATE ${ARGN})
  endif()
endfunction()
